import { useEffect, useRef, useState } from 'react'
import { CanvasRuntime } from './CanvasRuntime'
import { WebBehaviorRuntime, type BehaviorDocument } from '../behaviorRuntime'
import { emptyRuntime, runtimeValues, type RuntimeMessage, type RuntimeState } from '../protocol/runtime'
import type { Bootstrap } from '../protocol/bootstrap'

const base64 = (value: string) => btoa(unescape(encodeURIComponent(value))).replaceAll('+', '-').replaceAll('/', '_').replaceAll('=', '')
export function WebRendererApp() {
  const encoded = location.pathname.startsWith('/render/') ? location.pathname.slice('/render/'.length) : null
  const [bootstrap, setBootstrap] = useState<Bootstrap | null>(null); const [error, setError] = useState<string | null>(null); const [windows, setWindows] = useState<{ fullWindowType: string; displayName: string }[]>([])
  const [runtime, setRuntime] = useState<RuntimeState>(emptyRuntime); const runtimeRef = useRef<RuntimeState>(emptyRuntime()); const behavior = useRef(new WebBehaviorRuntime())
  useEffect(() => { const load = () => { if (!encoded) return fetch('/api/windows').then(response => response.json()).then(setWindows).catch(() => setError('无法读取窗口列表。')); return fetch(`/api/bootstrap/${encoded}`).then(async response => response.ok ? response.json() : Promise.reject(await response.json())).then((value: Bootstrap) => { if (!value?.Layout) throw new Error('Bootstrap schema is invalid.'); setBootstrap(value); setError(null) }).catch(() => setError('无法加载或验证布局 bootstrap。')) }; void load(); const scheme = location.protocol === 'https:' ? 'wss' : 'ws'; let closed = false; let retry: number | undefined; const connect = () => { const socket = new WebSocket(`${scheme}://${location.host}/ws`); socket.onopen = () => { socket.send(JSON.stringify({ type: 'page.attach', fullWindowType: encoded })); void load() }; socket.onmessage = event => { try { const message = JSON.parse(event.data) as RuntimeMessage; if (message.type === 'bootstrap.changed') { behavior.current.dispose(); const empty = emptyRuntime(); runtimeRef.current = empty; setRuntime(empty); void load(); return } if (message.type === 'behavior.event' && message.payload) { behavior.current.publish(message.payload as never); return } const payload = message.payload; if (!payload || payload.SchemaVersion !== 1 || typeof payload.Sequence !== 'number') return; const previous = runtimeRef.current; const generation = payload.Generation ?? 0; if (message.type === 'snapshot' && (generation > previous.generation || generation === previous.generation && payload.Sequence > previous.sequence)) { const next = { values: runtimeValues(payload.Values ?? {}), sequence: payload.Sequence, generation }; runtimeRef.current = next; setRuntime(next) } else if (message.type === 'bindingPatch' && generation === previous.generation && payload.Sequence > previous.sequence) { const next = { values: { ...previous.values, ...runtimeValues(payload.Values ?? {}) }, sequence: payload.Sequence, generation }; runtimeRef.current = next; setRuntime(next) } } catch { setError('收到无效的实时状态消息。') } }; socket.onclose = () => { if (!closed) retry = window.setTimeout(connect, 1000) }; return socket }; const socket = connect(); return () => { closed = true; behavior.current.dispose(); if (retry) clearTimeout(retry); socket.close() } }, [encoded])
  useEffect(() => { behavior.current.replace(bootstrap?.BehaviorDocument as BehaviorDocument | undefined) }, [bootstrap])
  if (!encoded) return <main className="window-index"><h1>Web Renderer</h1>{windows.map(window => <a key={window.fullWindowType} href={`/render/${base64(window.fullWindowType)}`}>{window.displayName}</a>)}</main>
  if (error || !bootstrap?.Layout) return <main className="error-page"><h1>布局无法渲染</h1><p>{error ?? bootstrap?.Diagnostics.join('\n') ?? 'LayoutMissing'}</p></main>
  return <CanvasRuntime bootstrap={bootstrap} runtime={runtime} />
}
