<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <RootNamespace>neo_bpsys_wpf.Core</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseWpf>true</UseWpf>
        <CETCompat>false</CETCompat>
        <Configurations>Debug;Release;Beta;Preview</Configurations>
		<AssemblyVersion>3.0.0.0</AssemblyVersion>
		<Version>3.0.7</Version>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Platforms>AnyCPU;x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="build\**" />
      <EmbeddedResource Remove="build\**" />
      <None Remove="build\**" />
      <Page Remove="build\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.10" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="Downloader" Version="5.9.5" />
        <PackageReference Include="hyjiacan.pinyin4net" Version="4.1.1" />
        <PackageReference Include="SkiaSharp" Version="4.151.0" />
        <PackageReference Include="WPF-UI" Version="4.3.0" />
    </ItemGroup>

</Project>
