export type BaseConfig = { ControlType: string; BehaviorGuid?: string; Left?: number; Top?: number; Width?: number | null; Height?: number | null; ZIndex?: number; Visibility?: string | number; IsGaussianBlurEnabled?: boolean; GaussianBlurRadius?: number; BindingPath?: string | null }
export type TextBinding = { Sources?: { Path?: string }[]; StringFormat?: string; JoinSeparator?: string; NullText?: string; FallbackText?: string }
export type TextStyle = { Width?: number | null; Height?: number | null; HorizontalAlignment?: string | number; VerticalAlignment?: string | number; TextAlignment?: string | number; TextWrapping?: string | number; FontFamily?: string; FontWeight?: string; Color?: string; ColorBindingPath?: string; FontSize?: number }
export type TextConfig = BaseConfig & TextStyle & { ControlType: 'Text'; Text?: string; TextBinding?: TextBinding }
export type LocalizedTextConfig = BaseConfig & TextStyle & { ControlType: 'LocalizedText' }
export type MapNameConfig = BaseConfig & TextStyle & { ControlType: 'MapNameText'; EmptyText?: string }
export type GameProgressConfig = BaseConfig & TextStyle & { ControlType: 'GameProgressText'; DisplayMode?: string | number; VerticalLanguageMode?: string | number; LatinVerticalMode?: string | number; VerticalDirection?: string | number; DisplayLanguage?: string | number; NumberStyle?: string | number; VerticalTextSpacing?: number; GroupSpacing?: number; ShowSeparator?: boolean; SeparatorThickness?: number; SeparatorColor?: string; BackgroundColor?: string; PaddingLeft?: number; PaddingTop?: number; PaddingRight?: number; PaddingBottom?: number }
export type ShapeConfig = BaseConfig & { ControlType: 'Rectangle' | 'Polygon'; RadiusX?: number; RadiusY?: number; FillMode?: string | number; UseGradient?: boolean; FillColor?: string; FillBindingPath?: string; GradientEndColor?: string; GradientEndBindingPath?: string; GradientAngle?: number; StrokeColor?: string; StrokeThickness?: number; Points?: { X?: number; Y?: number }[] }
export type ImageConfig = BaseConfig & { ControlType: 'Image' | 'BorderedImage'; ImagePath?: string; ImageWidth?: number; ImageHeight?: number; Stretch?: string | number; SizingMode?: string | number; HorizontalAlignment?: string | number; VerticalAlignment?: string | number; ClipToBounds?: boolean; CornerRadius?: number; Lockable?: boolean; LockImagePath?: string; LockVisibilityBindingPath?: string; LockVisibleWhen?: string | number; LockZIndexOffset?: number; PickingBorderAvailable?: boolean; PickingBorderImagePath?: string; PickingBorderName?: string; PickingBorderZIndexOffset?: number; PickingBorderFillColor?: string }
export type MapV2Part = { Part?: string | number; X?: number; Y?: number; Width?: number; Height?: number }
export type MapV2DisplayConfig = BaseConfig & { ControlType: 'MapV2Display'; MapKey?: string; MapNameFontFamily?: string; MapNameFontWeight?: string; MapNameColor?: string; MapNameFontSize?: number; TeamNameFontFamily?: string; TeamNameFontWeight?: string; TeamNameColor?: string; TeamNameFontSize?: number; CampNameFontFamily?: string; CampNameFontWeight?: string; CampNameColor?: string; CampNameFontSize?: number; MapBorderNormalColor?: string; MapBorderBannedColor?: string; PickingBorderImagePath?: string; PickingBorderFillColor?: string; InternalParts?: MapV2Part[] }
export type BackgroundTintConfig = BaseConfig & { ControlType: 'BackgroundTintRectangle' | 'BackgroundTintPolygon'; TintColor?: string; TintBindingPath?: string; TintMode?: string | number; TintStrength?: number; TextureStrength?: number; RadiusX?: number; RadiusY?: number; Points?: { X?: number; Y?: number }[] }
export type UnsupportedConfig = BaseConfig & { ControlType: 'GlobalScoreRow' | 'TalentTraitDisplay' }
export type ControlConfig = TextConfig | LocalizedTextConfig | MapNameConfig | GameProgressConfig | ShapeConfig | ImageConfig | BackgroundTintConfig | MapV2DisplayConfig | UnsupportedConfig

export const finite = (value: unknown, fallback = 0): number => typeof value === 'number' && Number.isFinite(value) ? value : fallback
export const text = (value: unknown): string | undefined => typeof value === 'string' ? value : undefined
