<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <RootNamespace>neo_bpsys_wpf.PluginSdk</RootNamespace>
        <Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>0.3.0</Version>
		<Platforms>AnyCPU;x64</Platforms>
    </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\neo-bpsys-wpf.Core\neo-bpsys-wpf.Core.csproj" IncludeAssets="all" />
    </ItemGroup>
</Project>
