import { useEffect, useState } from 'react'
import type { CSSProperties } from 'react'
import type { RuntimeState, WebRuntimeAsset } from '../../protocol/runtime'
import type { ImageConfig } from '../controlTypes'
import { finite } from '../controlTypes'
import { horizontal, vertical } from '../alignment'

const fit = (value: unknown): CSSProperties['objectFit'] => ({ Fill: 'fill', Uniform: 'contain', UniformToFill: 'cover', None: 'none' })[String(value)] as CSSProperties['objectFit'] ?? 'fill'
const lockVisible = (config: ImageConfig, runtime: RuntimeState) => { if (!config.Lockable) return false; if (!config.LockVisibilityBindingPath) return config.LockVisibleWhen === 'Always'; const value = runtime.values[config.LockVisibilityBindingPath]; return config.LockVisibleWhen === 'VisibleWhenFalse' ? value === false : value === true }
function DynamicImage({ source, style }: { source?: string; style: CSSProperties }) { const [current, setCurrent] = useState<string | undefined>(source); useEffect(() => { if (source) setCurrent(source) }, [source]); return current ? <img src={current} style={style} /> : null }
function ImageLayers({ name, config, runtime, resources }: { name: string; config: ImageConfig; runtime: RuntimeState; resources: Record<string, string> }) {
  const asset = config.BindingPath ? runtime.values[config.BindingPath] as WebRuntimeAsset | undefined : undefined; const source = asset?.Kind === 'image' ? asset.Url : !config.BindingPath ? resources[config.ImagePath ?? ''] : undefined
  const sizing = String(config.SizingMode ?? 'Auto'); const imageStyle: CSSProperties = { objectFit: fit(config.Stretch), width: config.ImageWidth ?? (sizing === 'FillContainer' ? '100%' : undefined), height: config.ImageHeight ?? (sizing === 'FillContainer' ? '100%' : undefined), justifySelf: horizontal(config.HorizontalAlignment), alignSelf: vertical(config.VerticalAlignment) }
  return <><div data-behavior-content style={{ display: 'grid', width: '100%', height: '100%', overflow: sizing === 'OverflowCrop' ? 'hidden' : 'visible', placeItems: sizing === 'OverflowCrop' ? 'center' : undefined }}><DynamicImage source={source} style={imageStyle} /></div>
    {lockVisible(config, runtime) ? <img data-lock-overlay src={resources[config.LockImagePath ?? '']} style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', zIndex: finite(config.LockZIndexOffset, 1) }} /> : null}
    {config.PickingBorderAvailable ? <div data-animation-part="PickingBorder" data-picking-border style={{ position: 'absolute', inset: 0, zIndex: finite(config.PickingBorderZIndexOffset, 2), background: '#fff', maskImage: resources[config.PickingBorderImagePath ?? ''] ? `url(${resources[config.PickingBorderImagePath ?? '']})` : undefined, WebkitMaskImage: resources[config.PickingBorderImagePath ?? ''] ? `url(${resources[config.PickingBorderImagePath ?? '']})` : undefined, maskSize: '100% 100%', WebkitMaskSize: '100% 100%', opacity: 0 }} /> : null}</>
}
export function ImageRenderer({ name, config, runtime, resources }: { name: string; config: ImageConfig; runtime: RuntimeState; resources: Record<string, string> }) { return <div className="web-image" style={{ width: '100%', height: '100%', overflow: config.ClipToBounds || finite(config.CornerRadius) > 0 ? 'hidden' : 'visible', borderRadius: finite(config.CornerRadius) || undefined }}><ImageLayers name={name} config={config} runtime={runtime} resources={resources} /></div> }
export function BorderedImageRenderer({ name, config, runtime, resources }: { name: string; config: ImageConfig; runtime: RuntimeState; resources: Record<string, string> }) { return <div className="web-bordered-image" style={{ width: '100%', height: '100%', overflow: config.ClipToBounds ? 'hidden' : 'visible', borderRadius: finite(config.CornerRadius) || undefined }}><ImageLayers name={name} config={config} runtime={runtime} resources={resources} /></div> }
