import { useId } from 'react'
import type { RuntimeState } from '../../protocol/runtime'
import { color } from '../colors'
import { finite, type ShapeConfig } from '../controlTypes'

function points(angle: number): [number, number, number, number] { const n = ((angle % 360) + 360) % 360; if (n === 0) return [0, .5, 1, .5]; if (n === 90) return [.5, 0, .5, 1]; if (n === 180) return [1, .5, 0, .5]; if (n === 270) return [.5, 1, .5, 0]; const r = n * Math.PI / 180; const x = Math.cos(r); const y = Math.sin(r); const s = .5 / Math.max(Math.abs(x), Math.abs(y)); return [.5 - x * s, .5 - y * s, .5 + x * s, .5 + y * s] }
function fill(config: ShapeConfig, runtime: RuntimeState, id: string) { const gradient = config.UseGradient || config.FillMode === 'LinearGradient' || config.FillMode === 1; if (!gradient) return { fill: color(config.FillBindingPath ? runtime.values[config.FillBindingPath] : config.FillColor, 'transparent') }; const [x1,y1,x2,y2] = points(finite(config.GradientAngle)); const start = color(config.FillBindingPath ? runtime.values[config.FillBindingPath] : config.FillColor, '#fff'); const end = color(config.GradientEndBindingPath ? runtime.values[config.GradientEndBindingPath] : config.GradientEndColor, 'transparent'); return { fill: `url(#${id})`, definition: <linearGradient id={id} x1={x1} y1={y1} x2={x2} y2={y2}><stop offset="0" stopColor={start}/><stop offset="1" stopColor={end}/></linearGradient> } }
export function RectangleRenderer({ config, runtime }: { config: ShapeConfig; runtime: RuntimeState }) { const id = useId().replaceAll(':',''); const paint = fill(config, runtime, id); return <svg width="100%" height="100%" viewBox="0 0 1 1" preserveAspectRatio="none"><defs>{paint.definition}</defs><rect width="1" height="1" rx={Math.max(0, finite(config.RadiusX))} ry={Math.max(0, finite(config.RadiusY))} fill={paint.fill} stroke={color(config.StrokeColor)} strokeWidth={Math.max(0, finite(config.StrokeThickness))}/></svg> }
export function PolygonRenderer({ config, runtime }: { config: ShapeConfig; runtime: RuntimeState }) { const id = useId().replaceAll(':',''); const valid = (config.Points ?? []).filter(point => Number.isFinite(point.X) && Number.isFinite(point.Y)); const vertices = valid.length >= 3 ? valid : [{X:.5,Y:0},{X:1,Y:1},{X:0,Y:1}]; const paint = fill(config, runtime, id); return <svg width="100%" height="100%" viewBox="0 0 1 1" preserveAspectRatio="none"><defs>{paint.definition}</defs><polygon points={vertices.map(point => `${point.X},${point.Y}`).join(' ')} fill={paint.fill} stroke={color(config.StrokeColor)} strokeWidth={Math.max(0, finite(config.StrokeThickness))}/></svg> }
