//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace neo_bpsys_wpf.Assets.Locales {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("neo_bpsys_wpf.Assets.Locales.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Abnormal 的本地化字符串。
        /// </summary>
        public static string Abnormal {
            get {
                return ResourceManager.GetString("Abnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add player 的本地化字符串。
        /// </summary>
        public static string AddPlayer {
            get {
                return ResourceManager.GetString("AddPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All frontend windows 的本地化字符串。
        /// </summary>
        public static string AllFrontendWindows {
            get {
                return ResourceManager.GetString("AllFrontendWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A modern IdentityV BP software 的本地化字符串。
        /// </summary>
        public static string AModernIdentityVBPSoftware {
            get {
                return ResourceManager.GetString("AModernIdentityVBPSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Made by Zero_PLFJY | Auther&apos;s QQ: 3424127335 | Software feedback group(QQ): 175741665 的本地化字符串。
        /// </summary>
        public static string AutherDetails {
            get {
                return ResourceManager.GetString("AutherDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Away team:  的本地化字符串。
        /// </summary>
        public static string AwayTeamColon {
            get {
                return ResourceManager.GetString("AwayTeamColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Away team information 的本地化字符串。
        /// </summary>
        public static string AwayTeamInformation {
            get {
                return ResourceManager.GetString("AwayTeamInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backend management 的本地化字符串。
        /// </summary>
        public static string BackendManagement {
            get {
                return ResourceManager.GetString("BackendManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ban Hunter 的本地化字符串。
        /// </summary>
        public static string BanHun {
            get {
                return ResourceManager.GetString("BanHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ban number control 的本地化字符串。
        /// </summary>
        public static string BanNumberControl {
            get {
                return ResourceManager.GetString("BanNumberControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ban Survivor 的本地化字符串。
        /// </summary>
        public static string BanSur {
            get {
                return ResourceManager.GetString("BanSur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Black 的本地化字符串。
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blink 的本地化字符串。
        /// </summary>
        public static string Blink {
            get {
                return ResourceManager.GetString("Blink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BP overview 的本地化字符串。
        /// </summary>
        public static string BPOverview {
            get {
                return ResourceManager.GetString("BPOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BP window 的本地化字符串。
        /// </summary>
        public static string BPWindow {
            get {
                return ResourceManager.GetString("BPWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BP background 的本地化字符串。
        /// </summary>
        public static string BPWindowImages {
            get {
                return ResourceManager.GetString("BPWindowImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Camp color in score statistics 的本地化字符串。
        /// </summary>
        public static string CampIconColorInScoreStatistics {
            get {
                return ResourceManager.GetString("CampIconColorInScoreStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Camp icon color(MapBPV2) 的本地化字符串。
        /// </summary>
        public static string CampIconColorOfMapBPV2 {
            get {
                return ResourceManager.GetString("CampIconColorOfMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Camp of away team 的本地化字符串。
        /// </summary>
        public static string CampOfAwayTeam {
            get {
                return ResourceManager.GetString("CampOfAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Camp of home team 的本地化字符串。
        /// </summary>
        public static string CampOfHomeTeam {
            get {
                return ResourceManager.GetString("CampOfHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character name 的本地化字符串。
        /// </summary>
        public static string CharacterName {
            get {
                return ResourceManager.GetString("CharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for updates 的本地化字符串。
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close all 的本地化字符串。
        /// </summary>
        public static string CloseAll {
            get {
                return ResourceManager.GetString("CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color of talent and trait icon 的本地化字符串。
        /// </summary>
        public static string ColorOfTalentAndTraitIcon {
            get {
                return ResourceManager.GetString("ColorOfTalentAndTraitIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contributor list 的本地化字符串。
        /// </summary>
        public static string ContributorList {
            get {
                return ResourceManager.GetString("ContributorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control first 2 picking border separately 的本地化字符串。
        /// </summary>
        public static string ControlFirst2PickingBorderSeparately {
            get {
                return ResourceManager.GetString("ControlFirst2PickingBorderSeparately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control manually 的本地化字符串。
        /// </summary>
        public static string ControlManually {
            get {
                return ResourceManager.GetString("ControlManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count down 的本地化字符串。
        /// </summary>
        public static string CountDown {
            get {
                return ResourceManager.GetString("CountDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current ban 的本地化字符串。
        /// </summary>
        public static string CurrentBan {
            get {
                return ResourceManager.GetString("CurrentBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current ban lock 的本地化字符串。
        /// </summary>
        public static string CurrentBanLock {
            get {
                return ResourceManager.GetString("CurrentBanLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current ban lock(BP overview) 的本地化字符串。
        /// </summary>
        public static string CurrentBanLockOfBPOverview {
            get {
                return ResourceManager.GetString("CurrentBanLockOfBPOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current hunter team:    的本地化字符串。
        /// </summary>
        public static string CurrentHunterTeamColon {
            get {
                return ResourceManager.GetString("CurrentHunterTeamColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current player on stage 的本地化字符串。
        /// </summary>
        public static string CurrentPlayerOnStage {
            get {
                return ResourceManager.GetString("CurrentPlayerOnStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current status:  的本地化字符串。
        /// </summary>
        public static string CurrentStatusColon {
            get {
                return ResourceManager.GetString("CurrentStatusColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current survivor team:  的本地化字符串。
        /// </summary>
        public static string CurrentSurvivorTeamColon {
            get {
                return ResourceManager.GetString("CurrentSurvivorTeamColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize BP window 的本地化字符串。
        /// </summary>
        public static string CustomizeBPWindow {
            get {
                return ResourceManager.GetString("CustomizeBPWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize frontend UI 的本地化字符串。
        /// </summary>
        public static string CustomizeFrontendUI {
            get {
                return ResourceManager.GetString("CustomizeFrontendUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize game data window 的本地化字符串。
        /// </summary>
        public static string CustomizeGameDataWindow {
            get {
                return ResourceManager.GetString("CustomizeGameDataWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize interclude window 的本地化字符串。
        /// </summary>
        public static string CustomizeIntercludeWindow {
            get {
                return ResourceManager.GetString("CustomizeIntercludeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize score window 的本地化字符串。
        /// </summary>
        public static string CustomizeScoreWindow {
            get {
                return ResourceManager.GetString("CustomizeScoreWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CustomizeWidgetWindow 的本地化字符串。
        /// </summary>
        public static string CustomizeWidgetWindow {
            get {
                return ResourceManager.GetString("CustomizeWidgetWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug options 的本地化字符串。
        /// </summary>
        public static string DebugOptions {
            get {
                return ResourceManager.GetString("DebugOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Design mode 的本地化字符串。
        /// </summary>
        public static string DesignMode {
            get {
                return ResourceManager.GetString("DesignMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distance 的本地化字符串。
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Documentations 的本地化字符串。
        /// </summary>
        public static string Documentations {
            get {
                return ResourceManager.GetString("Documentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download preview version? 的本地化字符串。
        /// </summary>
        public static string DownloadPreviewVersion {
            get {
                return ResourceManager.GetString("DownloadPreviewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download progress:  的本地化字符串。
        /// </summary>
        public static string DownloadProgress {
            get {
                return ResourceManager.GetString("DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download source:  的本地化字符串。
        /// </summary>
        public static string DownloadSource {
            get {
                return ResourceManager.GetString("DownloadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw 的本地化字符串。
        /// </summary>
        public static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit game data background image 的本地化字符串。
        /// </summary>
        public static string EditGameDataBackgroundImage {
            get {
                return ResourceManager.GetString("EditGameDataBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit image 的本地化字符串。
        /// </summary>
        public static string EditImage {
            get {
                return ResourceManager.GetString("EditImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit interclude background image 的本地化字符串。
        /// </summary>
        public static string EditIntercludeBackgroundImage {
            get {
                return ResourceManager.GetString("EditIntercludeBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit text property 的本地化字符串。
        /// </summary>
        public static string EditTextProperty {
            get {
                return ResourceManager.GetString("EditTextProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End game guidance 的本地化字符串。
        /// </summary>
        public static string EndGameGuidance {
            get {
                return ResourceManager.GetString("EndGameGuidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter 的本地化字符串。
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exchange camp 的本地化字符串。
        /// </summary>
        public static string ExchangeCamp {
            get {
                return ResourceManager.GetString("ExchangeCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excitement 的本地化字符串。
        /// </summary>
        public static string Excitement {
            get {
                return ResourceManager.GetString("Excitement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export UI configuration 的本地化字符串。
        /// </summary>
        public static string ExportUIConfig {
            get {
                return ResourceManager.GetString("ExportUIConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extensions 的本地化字符串。
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format:  的本地化字符串。
        /// </summary>
        public static string FormatColon {
            get {
                return ResourceManager.GetString("FormatColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4 Eliminate 的本地化字符串。
        /// </summary>
        public static string FourEliminate {
            get {
                return ResourceManager.GetString("FourEliminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4 escape 的本地化字符串。
        /// </summary>
        public static string FourEscape {
            get {
                return ResourceManager.GetString("FourEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free Game 的本地化字符串。
        /// </summary>
        public static string FreeGame {
            get {
                return ResourceManager.GetString("FreeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frontend Management 的本地化字符串。
        /// </summary>
        public static string FrontManage {
            get {
                return ResourceManager.GetString("FrontManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 1 First Half 的本地化字符串。
        /// </summary>
        public static string Game1FirstHalf {
            get {
                return ResourceManager.GetString("Game1FirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 1 Second Half 的本地化字符串。
        /// </summary>
        public static string Game1SecondHalf {
            get {
                return ResourceManager.GetString("Game1SecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 2 First Half 的本地化字符串。
        /// </summary>
        public static string Game2FirstHalf {
            get {
                return ResourceManager.GetString("Game2FirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 2 Second Half 的本地化字符串。
        /// </summary>
        public static string Game2SecondHalf {
            get {
                return ResourceManager.GetString("Game2SecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 3 Extra First Half 的本地化字符串。
        /// </summary>
        public static string Game3ExtraFirstHalf {
            get {
                return ResourceManager.GetString("Game3ExtraFirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 3 Extra Second Half 的本地化字符串。
        /// </summary>
        public static string Game3ExtraSecondHalf {
            get {
                return ResourceManager.GetString("Game3ExtraSecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 3 First Half 的本地化字符串。
        /// </summary>
        public static string Game3FirstHalf {
            get {
                return ResourceManager.GetString("Game3FirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 3 Second Half 的本地化字符串。
        /// </summary>
        public static string Game3SecondHalf {
            get {
                return ResourceManager.GetString("Game3SecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 4 First Half 的本地化字符串。
        /// </summary>
        public static string Game4FirstHalf {
            get {
                return ResourceManager.GetString("Game4FirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 4 Second Half 的本地化字符串。
        /// </summary>
        public static string Game4SecondHalf {
            get {
                return ResourceManager.GetString("Game4SecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 5 Extra First Half 的本地化字符串。
        /// </summary>
        public static string Game5ExtraFirstHalf {
            get {
                return ResourceManager.GetString("Game5ExtraFirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 5 Extra Second Half 的本地化字符串。
        /// </summary>
        public static string Game5ExtraSecondHalf {
            get {
                return ResourceManager.GetString("Game5ExtraSecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 5 First Half 的本地化字符串。
        /// </summary>
        public static string Game5FirstHalf {
            get {
                return ResourceManager.GetString("Game5FirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 5 Second Half 的本地化字符串。
        /// </summary>
        public static string Game5SecondHalf {
            get {
                return ResourceManager.GetString("Game5SecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Data 的本地化字符串。
        /// </summary>
        public static string GameData {
            get {
                return ResourceManager.GetString("GameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game progress:  的本地化字符串。
        /// </summary>
        public static string GameProgressColon {
            get {
                return ResourceManager.GetString("GameProgressColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game result 的本地化字符串。
        /// </summary>
        public static string GameResult {
            get {
                return ResourceManager.GetString("GameResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game selection 的本地化字符串。
        /// </summary>
        public static string GameSelection {
            get {
                return ResourceManager.GetString("GameSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game statistics window 的本地化字符串。
        /// </summary>
        public static string GameStatisticsWindow {
            get {
                return ResourceManager.GetString("GameStatisticsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global ban 的本地化字符串。
        /// </summary>
        public static string GlobalBan {
            get {
                return ResourceManager.GetString("GlobalBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global ban hunter 的本地化字符串。
        /// </summary>
        public static string GlobalBanHunter {
            get {
                return ResourceManager.GetString("GlobalBanHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global ban lock 的本地化字符串。
        /// </summary>
        public static string GlobalBanLock {
            get {
                return ResourceManager.GetString("GlobalBanLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global ban lock(BP Overview) 的本地化字符串。
        /// </summary>
        public static string GlobalBanLockOfBPOverview {
            get {
                return ResourceManager.GetString("GlobalBanLockOfBPOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global ban record 的本地化字符串。
        /// </summary>
        public static string GlobalBanRecord {
            get {
                return ResourceManager.GetString("GlobalBanRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global ban survivor 的本地化字符串。
        /// </summary>
        public static string GlobalBanSurvivor {
            get {
                return ResourceManager.GetString("GlobalBanSurvivor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home team:  的本地化字符串。
        /// </summary>
        public static string HomeTeamColon {
            get {
                return ResourceManager.GetString("HomeTeamColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home team information 的本地化字符串。
        /// </summary>
        public static string HomeTeamInformation {
            get {
                return ResourceManager.GetString("HomeTeamInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home team name 的本地化字符串。
        /// </summary>
        public static string HomeTeamName {
            get {
                return ResourceManager.GetString("HomeTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hunter 的本地化字符串。
        /// </summary>
        public static string Hunter {
            get {
                return ResourceManager.GetString("Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hunter icon(Map BP V2) 的本地化字符串。
        /// </summary>
        public static string HunterIconOfMapBPV2 {
            get {
                return ResourceManager.GetString("HunterIconOfMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hunter picking border 的本地化字符串。
        /// </summary>
        public static string HunterPickingBorder {
            get {
                return ResourceManager.GetString("HunterPickingBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hunter player 的本地化字符串。
        /// </summary>
        public static string HunterPlayer {
            get {
                return ResourceManager.GetString("HunterPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hunter score in game 的本地化字符串。
        /// </summary>
        public static string HunterScoreInGame {
            get {
                return ResourceManager.GetString("HunterScoreInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hunter talent 的本地化字符串。
        /// </summary>
        public static string HunterTalent {
            get {
                return ResourceManager.GetString("HunterTalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hunter trait 的本地化字符串。
        /// </summary>
        public static string HunterTrait {
            get {
                return ResourceManager.GetString("HunterTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import from json file 的本地化字符串。
        /// </summary>
        public static string ImportFromJsonFile {
            get {
                return ResourceManager.GetString("ImportFromJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import UI configuration 的本地化字符串。
        /// </summary>
        public static string ImportUIConfig {
            get {
                return ResourceManager.GetString("ImportUIConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install 的本地化字符串。
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interclude window 的本地化字符串。
        /// </summary>
        public static string IntercludeWindow {
            get {
                return ResourceManager.GetString("IntercludeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is game finished 的本地化字符串。
        /// </summary>
        public static string IsGameFinished {
            get {
                return ResourceManager.GetString("IsGameFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is visible 的本地化字符串。
        /// </summary>
        public static string IsVisible {
            get {
                return ResourceManager.GetString("IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is used for fast import. The example files are  neo-bpsys-wpf\Resources\队伍信息导入示例-xxx.json. Check the documentations for more details.  的本地化字符串。
        /// </summary>
        public static string JsonImportTip {
            get {
                return ResourceManager.GetString("JsonImportTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language setting 的本地化字符串。
        /// </summary>
        public static string LanguageSetting {
            get {
                return ResourceManager.GetString("LanguageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last step 的本地化字符串。
        /// </summary>
        public static string LastStep {
            get {
                return ResourceManager.GetString("LastStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Listen 的本地化字符串。
        /// </summary>
        public static string Listen {
            get {
                return ResourceManager.GetString("Listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Made by Zero_PLFJY 的本地化字符串。
        /// </summary>
        public static string MadeByZeroPLFJY {
            get {
                return ResourceManager.GetString("MadeByZeroPLFJY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map ban 的本地化字符串。
        /// </summary>
        public static string MapBan {
            get {
                return ResourceManager.GetString("MapBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map BP 的本地化字符串。
        /// </summary>
        public static string MapBP {
            get {
                return ResourceManager.GetString("MapBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map BP background 的本地化字符串。
        /// </summary>
        public static string MapBPBackground {
            get {
                return ResourceManager.GetString("MapBPBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map BP V2 background 的本地化字符串。
        /// </summary>
        public static string MapBPV2Background {
            get {
                return ResourceManager.GetString("MapBPV2Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map pick 的本地化字符串。
        /// </summary>
        public static string MapPick {
            get {
                return ResourceManager.GetString("MapPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New game 的本地化字符串。
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next step 的本地化字符串。
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: All layout changes of score statistics will NOT be saved in BO3 mode 的本地化字符串。
        /// </summary>
        public static string NoteScoreStatisticsNotSaveInBO3Mode {
            get {
                return ResourceManager.GetString("NoteScoreStatisticsNotSaveInBO3Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 st/rd/nd/th 的本地化字符串。
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Official website 的本地化字符串。
        /// </summary>
        public static string OfficialWebsite {
            get {
                return ResourceManager.GetString("OfficialWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open all 的本地化字符串。
        /// </summary>
        public static string OpenAll {
            get {
                return ResourceManager.GetString("OpenAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the frontend config file directory 的本地化字符串。
        /// </summary>
        public static string OpenFrontendDirectory {
            get {
                return ResourceManager.GetString("OpenFrontendDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the game file output directory 的本地化字符串。
        /// </summary>
        public static string OpenGameFileDirectory {
            get {
                return ResourceManager.GetString("OpenGameFileDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open log directory 的本地化字符串。
        /// </summary>
        public static string OpenLogDirectory {
            get {
                return ResourceManager.GetString("OpenLogDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open picking border |  的本地化字符串。
        /// </summary>
        public static string OpenPickingBorder {
            get {
                return ResourceManager.GetString("OpenPickingBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open source repositories used by our project:  的本地化字符串。
        /// </summary>
        public static string OpenSourceRepositoryUsed {
            get {
                return ResourceManager.GetString("OpenSourceRepositoryUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operate team:  的本地化字符串。
        /// </summary>
        public static string OperateTeam {
            get {
                return ResourceManager.GetString("OperateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patroller 的本地化字符串。
        /// </summary>
        public static string Patroller {
            get {
                return ResourceManager.GetString("Patroller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Peeper 的本地化字符串。
        /// </summary>
        public static string Peeper {
            get {
                return ResourceManager.GetString("Peeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character Selection 的本地化字符串。
        /// </summary>
        public static string Pick {
            get {
                return ResourceManager.GetString("Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick hunter 的本地化字符串。
        /// </summary>
        public static string PickHunter {
            get {
                return ResourceManager.GetString("PickHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picking border color(MapBPV2) 的本地化字符串。
        /// </summary>
        public static string PickingBorderColorOfMapBPV2 {
            get {
                return ResourceManager.GetString("PickingBorderColorOfMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picking border image 的本地化字符串。
        /// </summary>
        public static string PickingBorderImage {
            get {
                return ResourceManager.GetString("PickingBorderImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picking border image color(It will cover the color of picking border itself) 的本地化字符串。
        /// </summary>
        public static string PickingBorderImageColor {
            get {
                return ResourceManager.GetString("PickingBorderImageColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picking border(Map BP V2) 的本地化字符串。
        /// </summary>
        public static string PickingBorderOfMapBPV2 {
            get {
                return ResourceManager.GetString("PickingBorderOfMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick survivor 的本地化字符串。
        /// </summary>
        public static string PickSurvivor {
            get {
                return ResourceManager.GetString("PickSurvivor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player name 的本地化字符串。
        /// </summary>
        public static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview:  的本地化字符串。
        /// </summary>
        public static string PreviewColon {
            get {
                return ResourceManager.GetString("PreviewColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project repository:  的本地化字符串。
        /// </summary>
        public static string ProjectRepository {
            get {
                return ResourceManager.GetString("ProjectRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick access 的本地化字符串。
        /// </summary>
        public static string QuickAccess {
            get {
                return ResourceManager.GetString("QuickAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove photo 的本地化字符串。
        /// </summary>
        public static string RemovePhoto {
            get {
                return ResourceManager.GetString("RemovePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset all personalization settings 的本地化字符串。
        /// </summary>
        public static string ResetAllPersonalizationSettings {
            get {
                return ResourceManager.GetString("ResetAllPersonalizationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset all personalization settings of the window 的本地化字符串。
        /// </summary>
        public static string ResetAllPersonalizationSettingsOfTheWindow {
            get {
                return ResourceManager.GetString("ResetAllPersonalizationSettingsOfTheWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset all scores 的本地化字符串。
        /// </summary>
        public static string ResetAllScores {
            get {
                return ResourceManager.GetString("ResetAllScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset BP overview layout 的本地化字符串。
        /// </summary>
        public static string ResetBPOverviewLayout {
            get {
                return ResourceManager.GetString("ResetBPOverviewLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset game scores 的本地化字符串。
        /// </summary>
        public static string ResetGameScores {
            get {
                return ResourceManager.GetString("ResetGameScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset hunter score layout in game 的本地化字符串。
        /// </summary>
        public static string ResetHunterScoreLayoutInGame {
            get {
                return ResourceManager.GetString("ResetHunterScoreLayoutInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset layout 的本地化字符串。
        /// </summary>
        public static string ResetLayout {
            get {
                return ResourceManager.GetString("ResetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset map BP 的本地化字符串。
        /// </summary>
        public static string ResetMapBP {
            get {
                return ResourceManager.GetString("ResetMapBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset map BP layout 的本地化字符串。
        /// </summary>
        public static string ResetMapBPLayout {
            get {
                return ResourceManager.GetString("ResetMapBPLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset map BP V2 layout 的本地化字符串。
        /// </summary>
        public static string ResetMapBPV2Layout {
            get {
                return ResourceManager.GetString("ResetMapBPV2Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset score statistics layout 的本地化字符串。
        /// </summary>
        public static string ResetScoreStatisticsLayout {
            get {
                return ResourceManager.GetString("ResetScoreStatisticsLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset survivor score layout in game 的本地化字符串。
        /// </summary>
        public static string ResetSurvivorScoreLayoutInGame {
            get {
                return ResourceManager.GetString("ResetSurvivorScoreLayoutInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save and apply 的本地化字符串。
        /// </summary>
        public static string SaveAndApply {
            get {
                return ResourceManager.GetString("SaveAndApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save game information 的本地化字符串。
        /// </summary>
        public static string SaveGameInformation {
            get {
                return ResourceManager.GetString("SaveGameInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Score Control 的本地化字符串。
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Score conponent 的本地化字符串。
        /// </summary>
        public static string ScoreConponent {
            get {
                return ResourceManager.GetString("ScoreConponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Score in BP window and game 的本地化字符串。
        /// </summary>
        public static string ScoreInBPWindowAndGame {
            get {
                return ResourceManager.GetString("ScoreInBPWindowAndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Score settlement 的本地化字符串。
        /// </summary>
        public static string ScoreSettlement {
            get {
                return ResourceManager.GetString("ScoreSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Score statistics 的本地化字符串。
        /// </summary>
        public static string ScoreStatistics {
            get {
                return ResourceManager.GetString("ScoreStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Score statistics(BO3 mode) 的本地化字符串。
        /// </summary>
        public static string ScoreStatisticsBO3 {
            get {
                return ResourceManager.GetString("ScoreStatisticsBO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Score statistics(BO5 mode) 的本地化字符串。
        /// </summary>
        public static string ScoreStatisticsBO5 {
            get {
                return ResourceManager.GetString("ScoreStatisticsBO5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set photo 的本地化字符串。
        /// </summary>
        public static string SetPhoto {
            get {
                return ResourceManager.GetString("SetPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set team logo 的本地化字符串。
        /// </summary>
        public static string SetTeamLogo {
            get {
                return ResourceManager.GetString("SetTeamLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shift distance of total score when switching between BO3 and BO5 mode 的本地化字符串。
        /// </summary>
        public static string ShiftDistanceOfTotalScoreWhenSwitchingBetweenBO3AndBO5Mode {
            get {
                return ResourceManager.GetString("ShiftDistanceOfTotalScoreWhenSwitchingBetweenBO3AndBO5Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show camp 的本地化字符串。
        /// </summary>
        public static string ShowCamp {
            get {
                return ResourceManager.GetString("ShowCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show picking border 的本地化字符串。
        /// </summary>
        public static string ShowPickingBorder {
            get {
                return ResourceManager.GetString("ShowPickingBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software updates 的本地化字符串。
        /// </summary>
        public static string SoftwareUpdates {
            get {
                return ResourceManager.GetString("SoftwareUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source of image resources:  的本地化字符串。
        /// </summary>
        public static string SourceOfImageResources {
            get {
                return ResourceManager.GetString("SourceOfImageResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sponsor 的本地化字符串。
        /// </summary>
        public static string Sponsor {
            get {
                return ResourceManager.GetString("Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start game guidance 的本地化字符串。
        /// </summary>
        public static string StartGameGuidance {
            get {
                return ResourceManager.GetString("StartGameGuidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Survivor 的本地化字符串。
        /// </summary>
        public static string Survivor {
            get {
                return ResourceManager.GetString("Survivor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Survivor icon(Map BP V2) 的本地化字符串。
        /// </summary>
        public static string SurvivorIconOfMapBPV2 {
            get {
                return ResourceManager.GetString("SurvivorIconOfMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Survivor picking border 1 的本地化字符串。
        /// </summary>
        public static string SurvivorPickingBorder1 {
            get {
                return ResourceManager.GetString("SurvivorPickingBorder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Survivor picking border 1 &amp; 2 的本地化字符串。
        /// </summary>
        public static string SurvivorPickingBorder1and2 {
            get {
                return ResourceManager.GetString("SurvivorPickingBorder1and2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Survivor picking border 2 的本地化字符串。
        /// </summary>
        public static string SurvivorPickingBorder2 {
            get {
                return ResourceManager.GetString("SurvivorPickingBorder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Survivor picking border 3 的本地化字符串。
        /// </summary>
        public static string SurvivorPickingBorder3 {
            get {
                return ResourceManager.GetString("SurvivorPickingBorder3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Survivor picking border 4 的本地化字符串。
        /// </summary>
        public static string SurvivorPickingBorder4 {
            get {
                return ResourceManager.GetString("SurvivorPickingBorder4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Survivor player 的本地化字符串。
        /// </summary>
        public static string SurvivorPlayer {
            get {
                return ResourceManager.GetString("SurvivorPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Survivor score in game 的本地化字符串。
        /// </summary>
        public static string SurvivorScoreInGame {
            get {
                return ResourceManager.GetString("SurvivorScoreInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Survivor talent 的本地化字符串。
        /// </summary>
        public static string SurvivorTalent {
            get {
                return ResourceManager.GetString("SurvivorTalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Synchronize to frontend 的本地化字符串。
        /// </summary>
        public static string SynchronizeToFrontend {
            get {
                return ResourceManager.GetString("SynchronizeToFrontend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Talents &amp; Traits 的本地化字符串。
        /// </summary>
        public static string Talent {
            get {
                return ResourceManager.GetString("Talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Team Information 的本地化字符串。
        /// </summary>
        public static string TeamInfo {
            get {
                return ResourceManager.GetString("TeamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Team name 的本地化字符串。
        /// </summary>
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Teleport 的本地化字符串。
        /// </summary>
        public static string Teleport {
            get {
                return ResourceManager.GetString("Teleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 eliminate 的本地化字符串。
        /// </summary>
        public static string ThreeEliminate {
            get {
                return ResourceManager.GetString("ThreeEliminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 escape 的本地化字符串。
        /// </summary>
        public static string ThreeEscape {
            get {
                return ResourceManager.GetString("ThreeEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger GC collection manually 的本地化字符串。
        /// </summary>
        public static string TriggerGCCollectionManually {
            get {
                return ResourceManager.GetString("TriggerGCCollectionManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warp 的本地化字符串。
        /// </summary>
        public static string Warp {
            get {
                return ResourceManager.GetString("Warp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 White 的本地化字符串。
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Widgets 的本地化字符串。
        /// </summary>
        public static string Widgets {
            get {
                return ResourceManager.GetString("Widgets", resourceCulture);
            }
        }
    }
}
