//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neo_bpsys_wpf.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("neo_bpsys_wpf.Locales.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abnormal.
        /// </summary>
        public static string Abnormal {
            get {
                return ResourceManager.GetString("Abnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add player.
        /// </summary>
        public static string AddPlayer {
            get {
                return ResourceManager.GetString("AddPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All frontend windows.
        /// </summary>
        public static string AllFrontendWindows {
            get {
                return ResourceManager.GetString("AllFrontendWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A modern Identity V BP software.
        /// </summary>
        public static string AModernIdentityVBPSoftware {
            get {
                return ResourceManager.GetString("AModernIdentityVBPSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        public static string AreYouSureYouWantToExit {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arms Factory.
        /// </summary>
        public static string ArmsFactory {
            get {
                return ResourceManager.GetString("ArmsFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by Zero_PLFJY | Auther&apos;s QQ: 3424127335 | Software feedback group(QQ): 175741665.
        /// </summary>
        public static string AutherDetails {
            get {
                return ResourceManager.GetString("AutherDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away team: .
        /// </summary>
        public static string AwayTeam {
            get {
                return ResourceManager.GetString("AwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away team game score-1.
        /// </summary>
        public static string AwayTeamGameScoreMinus1 {
            get {
                return ResourceManager.GetString("AwayTeamGameScoreMinus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away team game score+1.
        /// </summary>
        public static string AwayTeamGameScorePlus1 {
            get {
                return ResourceManager.GetString("AwayTeamGameScorePlus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away team information.
        /// </summary>
        public static string AwayTeamInformation {
            get {
                return ResourceManager.GetString("AwayTeamInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away team tie-1.
        /// </summary>
        public static string AwayTeamTieMinus1 {
            get {
                return ResourceManager.GetString("AwayTeamTieMinus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away team tie+1.
        /// </summary>
        public static string AwayTeamTiePlus1 {
            get {
                return ResourceManager.GetString("AwayTeamTiePlus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AwayTeamWinMinus1.
        /// </summary>
        public static string AwayTeamWinMinus1 {
            get {
                return ResourceManager.GetString("AwayTeamWinMinus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away team win+1.
        /// </summary>
        public static string AwayTeamWinPlus1 {
            get {
                return ResourceManager.GetString("AwayTeamWinPlus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend.
        /// </summary>
        public static string Backend {
            get {
                return ResourceManager.GetString("Backend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban.
        /// </summary>
        public static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban Hunter.
        /// </summary>
        public static string BanHunter {
            get {
                return ResourceManager.GetString("BanHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban number control.
        /// </summary>
        public static string BanNumberControl {
            get {
                return ResourceManager.GetString("BanNumberControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban Survivor.
        /// </summary>
        public static string BanSurvivor {
            get {
                return ResourceManager.GetString("BanSurvivor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Ban&quot; word(Map BP).
        /// </summary>
        public static string BanWordInMapBP {
            get {
                return ResourceManager.GetString("BanWordInMapBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blink.
        /// </summary>
        public static string Blink {
            get {
                return ResourceManager.GetString("Blink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP overview.
        /// </summary>
        public static string BPOverview {
            get {
                return ResourceManager.GetString("BPOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP window.
        /// </summary>
        public static string BPWindow {
            get {
                return ResourceManager.GetString("BPWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP background.
        /// </summary>
        public static string BPWindowImages {
            get {
                return ResourceManager.GetString("BPWindowImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camp color in score statistics.
        /// </summary>
        public static string CampIconColorInScoreStatistics {
            get {
                return ResourceManager.GetString("CampIconColorInScoreStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camp icon color(MapBPV2).
        /// </summary>
        public static string CampIconColorOfMapBPV2 {
            get {
                return ResourceManager.GetString("CampIconColorOfMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camp name(Map BP V2).
        /// </summary>
        public static string CampNameInMapBPV2 {
            get {
                return ResourceManager.GetString("CampNameInMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camp of away team.
        /// </summary>
        public static string CampOfAwayTeam {
            get {
                return ResourceManager.GetString("CampOfAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camp of home team.
        /// </summary>
        public static string CampOfHomeTeam {
            get {
                return ResourceManager.GetString("CampOfHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character name.
        /// </summary>
        public static string CharacterName {
            get {
                return ResourceManager.GetString("CharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChinaTown.
        /// </summary>
        public static string ChinaTown {
            get {
                return ResourceManager.GetString("ChinaTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all.
        /// </summary>
        public static string CloseAll {
            get {
                return ResourceManager.GetString("CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of talent and trait icon.
        /// </summary>
        public static string ColorOfTalentAndTraitIcon {
            get {
                return ResourceManager.GetString("ColorOfTalentAndTraitIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How about we explore the area ahead of us later~.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containment time.
        /// </summary>
        public static string ContainmentTime {
            get {
                return ResourceManager.GetString("ContainmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributor list.
        /// </summary>
        public static string ContributorList {
            get {
                return ResourceManager.GetString("ContributorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control first 2 picking border separately.
        /// </summary>
        public static string ControlFirst2PickingBorderSeparately {
            get {
                return ResourceManager.GetString("ControlFirst2PickingBorderSeparately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control manually.
        /// </summary>
        public static string ControlManually {
            get {
                return ResourceManager.GetString("ControlManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count down.
        /// </summary>
        public static string CountDown {
            get {
                return ResourceManager.GetString("CountDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current ban.
        /// </summary>
        public static string CurrentBan {
            get {
                return ResourceManager.GetString("CurrentBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current ban lock.
        /// </summary>
        public static string CurrentBanLock {
            get {
                return ResourceManager.GetString("CurrentBanLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current ban lock(BP overview).
        /// </summary>
        public static string CurrentBanLockOfBPOverview {
            get {
                return ResourceManager.GetString("CurrentBanLockOfBPOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current hunter team:   .
        /// </summary>
        public static string CurrentHunterTeamColon {
            get {
                return ResourceManager.GetString("CurrentHunterTeamColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current player on stage.
        /// </summary>
        public static string CurrentPlayerOnStage {
            get {
                return ResourceManager.GetString("CurrentPlayerOnStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current status: .
        /// </summary>
        public static string CurrentStatusColon {
            get {
                return ResourceManager.GetString("CurrentStatusColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current survivor team: .
        /// </summary>
        public static string CurrentSurvivorTeamColon {
            get {
                return ResourceManager.GetString("CurrentSurvivorTeamColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize BP window.
        /// </summary>
        public static string CustomizeBPWindow {
            get {
                return ResourceManager.GetString("CustomizeBPWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize frontend UI.
        /// </summary>
        public static string CustomizeFrontendUI {
            get {
                return ResourceManager.GetString("CustomizeFrontendUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize game data window.
        /// </summary>
        public static string CustomizeGameDataWindow {
            get {
                return ResourceManager.GetString("CustomizeGameDataWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize interclude window.
        /// </summary>
        public static string CustomizeIntercludeWindow {
            get {
                return ResourceManager.GetString("CustomizeIntercludeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize score window.
        /// </summary>
        public static string CustomizeScoreWindow {
            get {
                return ResourceManager.GetString("CustomizeScoreWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomizeWidgetWindow.
        /// </summary>
        public static string CustomizeWidgetWindow {
            get {
                return ResourceManager.GetString("CustomizeWidgetWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darkwoods.
        /// </summary>
        public static string Darkwoods {
            get {
                return ResourceManager.GetString("Darkwoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug options.
        /// </summary>
        public static string DebugOptions {
            get {
                return ResourceManager.GetString("DebugOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding progress.
        /// </summary>
        public static string DecodingProgress {
            get {
                return ResourceManager.GetString("DecodingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design mode.
        /// </summary>
        public static string DesignMode {
            get {
                return ResourceManager.GetString("DesignMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentations.
        /// </summary>
        public static string Documentations {
            get {
                return ResourceManager.GetString("Documentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download preview version?.
        /// </summary>
        public static string DownloadPreviewVersion {
            get {
                return ResourceManager.GetString("DownloadPreviewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download progress: .
        /// </summary>
        public static string DownloadProgress {
            get {
                return ResourceManager.GetString("DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download source: .
        /// </summary>
        public static string DownloadSource {
            get {
                return ResourceManager.GetString("DownloadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit game data background image.
        /// </summary>
        public static string EditGameDataBackgroundImage {
            get {
                return ResourceManager.GetString("EditGameDataBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit image.
        /// </summary>
        public static string EditImage {
            get {
                return ResourceManager.GetString("EditImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit interclude background image.
        /// </summary>
        public static string EditIntercludeBackgroundImage {
            get {
                return ResourceManager.GetString("EditIntercludeBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit text property.
        /// </summary>
        public static string EditTextProperty {
            get {
                return ResourceManager.GetString("EditTextProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (Unitied States).
        /// </summary>
        public static string en_US {
            get {
                return ResourceManager.GetString("en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End game guidance.
        /// </summary>
        public static string EndGameGuidance {
            get {
                return ResourceManager.GetString("EndGameGuidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eversleeping Town.
        /// </summary>
        public static string EversleepingTown {
            get {
                return ResourceManager.GetString("EversleepingTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excitement.
        /// </summary>
        public static string Excitement {
            get {
                return ResourceManager.GetString("Excitement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export UI configuration.
        /// </summary>
        public static string ExportUIConfig {
            get {
                return ResourceManager.GetString("ExportUIConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        public static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow system.
        /// </summary>
        public static string FollowSystem {
            get {
                return ResourceManager.GetString("FollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: .
        /// </summary>
        public static string FormatColon {
            get {
                return ResourceManager.GetString("FormatColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Eliminate.
        /// </summary>
        public static string FourEliminate {
            get {
                return ResourceManager.GetString("FourEliminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Escape.
        /// </summary>
        public static string FourEscape {
            get {
                return ResourceManager.GetString("FourEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Game.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontend - BP.
        /// </summary>
        public static string FrontendBP {
            get {
                return ResourceManager.GetString("FrontendBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontend - CutScene Window.
        /// </summary>
        public static string FrontendCutScene {
            get {
                return ResourceManager.GetString("FrontendCutScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontend Management.
        /// </summary>
        public static string FrontendManagement {
            get {
                return ResourceManager.GetString("FrontendManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontend-Widgets.
        /// </summary>
        public static string FrontendWidgets {
            get {
                return ResourceManager.GetString("FrontendWidgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 1 First Half.
        /// </summary>
        public static string Game1FirstHalf {
            get {
                return ResourceManager.GetString("Game1FirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 1 Second Half.
        /// </summary>
        public static string Game1SecondHalf {
            get {
                return ResourceManager.GetString("Game1SecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 2 First Half.
        /// </summary>
        public static string Game2FirstHalf {
            get {
                return ResourceManager.GetString("Game2FirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 2 Second Half.
        /// </summary>
        public static string Game2SecondHalf {
            get {
                return ResourceManager.GetString("Game2SecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 3 Extra First Half.
        /// </summary>
        public static string Game3ExtraFirstHalf {
            get {
                return ResourceManager.GetString("Game3ExtraFirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 3 Extra Second Half.
        /// </summary>
        public static string Game3ExtraSecondHalf {
            get {
                return ResourceManager.GetString("Game3ExtraSecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 3 First Half.
        /// </summary>
        public static string Game3FirstHalf {
            get {
                return ResourceManager.GetString("Game3FirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 3 Second Half.
        /// </summary>
        public static string Game3SecondHalf {
            get {
                return ResourceManager.GetString("Game3SecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 4 First Half.
        /// </summary>
        public static string Game4FirstHalf {
            get {
                return ResourceManager.GetString("Game4FirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 4 Second Half.
        /// </summary>
        public static string Game4SecondHalf {
            get {
                return ResourceManager.GetString("Game4SecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 5 Extra First Half.
        /// </summary>
        public static string Game5ExtraFirstHalf {
            get {
                return ResourceManager.GetString("Game5ExtraFirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 5 Extra Second Half.
        /// </summary>
        public static string Game5ExtraSecondHalf {
            get {
                return ResourceManager.GetString("Game5ExtraSecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 5 First Half.
        /// </summary>
        public static string Game5FirstHalf {
            get {
                return ResourceManager.GetString("Game5FirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 5 Second Half.
        /// </summary>
        public static string Game5SecondHalf {
            get {
                return ResourceManager.GetString("Game5SecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Data.
        /// </summary>
        public static string GameData {
            get {
                return ResourceManager.GetString("GameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game progress.
        /// </summary>
        public static string GameProgress {
            get {
                return ResourceManager.GetString("GameProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game progress: .
        /// </summary>
        public static string GameProgressColon {
            get {
                return ResourceManager.GetString("GameProgressColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game progress(Bp Overview).
        /// </summary>
        public static string GameProgressInBPOverview {
            get {
                return ResourceManager.GetString("GameProgressInBPOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game result.
        /// </summary>
        public static string GameResult {
            get {
                return ResourceManager.GetString("GameResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game scores.
        /// </summary>
        public static string GameScores {
            get {
                return ResourceManager.GetString("GameScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game scores(BP Overview).
        /// </summary>
        public static string GameScoresInBPOverview {
            get {
                return ResourceManager.GetString("GameScoresInBPOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game score(Score Statistics).
        /// </summary>
        public static string GameScoresInScoreStatistics {
            get {
                return ResourceManager.GetString("GameScoresInScoreStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game selection.
        /// </summary>
        public static string GameSelection {
            get {
                return ResourceManager.GetString("GameSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game statistics window.
        /// </summary>
        public static string GameStatisticsWindow {
            get {
                return ResourceManager.GetString("GameStatisticsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global ban.
        /// </summary>
        public static string GlobalBan {
            get {
                return ResourceManager.GetString("GlobalBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global ban hunter.
        /// </summary>
        public static string GlobalBanHunter {
            get {
                return ResourceManager.GetString("GlobalBanHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global ban lock.
        /// </summary>
        public static string GlobalBanLock {
            get {
                return ResourceManager.GetString("GlobalBanLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global ban lock(BP Overview).
        /// </summary>
        public static string GlobalBanLockOfBPOverview {
            get {
                return ResourceManager.GetString("GlobalBanLockOfBPOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global ban record.
        /// </summary>
        public static string GlobalBanRecord {
            get {
                return ResourceManager.GetString("GlobalBanRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global ban survivor.
        /// </summary>
        public static string GlobalBanSurvivor {
            get {
                return ResourceManager.GetString("GlobalBanSurvivor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heals.
        /// </summary>
        public static string Heals {
            get {
                return ResourceManager.GetString("Heals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Team.
        /// </summary>
        public static string HomeTeam {
            get {
                return ResourceManager.GetString("HomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home team game score-1.
        /// </summary>
        public static string HomeTeamGameScoreMinus1 {
            get {
                return ResourceManager.GetString("HomeTeamGameScoreMinus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home team game score+1.
        /// </summary>
        public static string HomeTeamGameScorePlus1 {
            get {
                return ResourceManager.GetString("HomeTeamGameScorePlus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home team information.
        /// </summary>
        public static string HomeTeamInformation {
            get {
                return ResourceManager.GetString("HomeTeamInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home team name.
        /// </summary>
        public static string HomeTeamName {
            get {
                return ResourceManager.GetString("HomeTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home team tie-1.
        /// </summary>
        public static string HomeTeamTieMinus1 {
            get {
                return ResourceManager.GetString("HomeTeamTieMinus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home team tie+1.
        /// </summary>
        public static string HomeTeamTiePlus1 {
            get {
                return ResourceManager.GetString("HomeTeamTiePlus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home team win-1.
        /// </summary>
        public static string HomeTeamWinMinus1 {
            get {
                return ResourceManager.GetString("HomeTeamWinMinus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home team win+1.
        /// </summary>
        public static string HomeTeamWinPlus1 {
            get {
                return ResourceManager.GetString("HomeTeamWinPlus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter.
        /// </summary>
        public static string Hun {
            get {
                return ResourceManager.GetString("Hun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter.
        /// </summary>
        public static string Hunter {
            get {
                return ResourceManager.GetString("Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter data.
        /// </summary>
        public static string HunterData {
            get {
                return ResourceManager.GetString("HunterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter icon(Map BP V2).
        /// </summary>
        public static string HunterIconOfMapBPV2 {
            get {
                return ResourceManager.GetString("HunterIconOfMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter picking border.
        /// </summary>
        public static string HunterPickingBorder {
            get {
                return ResourceManager.GetString("HunterPickingBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter player.
        /// </summary>
        public static string HunterPlayer {
            get {
                return ResourceManager.GetString("HunterPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter player ID.
        /// </summary>
        public static string HunterPlayerID {
            get {
                return ResourceManager.GetString("HunterPlayerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter score in game.
        /// </summary>
        public static string HunterScoreInGame {
            get {
                return ResourceManager.GetString("HunterScoreInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter talent.
        /// </summary>
        public static string HunterTalent {
            get {
                return ResourceManager.GetString("HunterTalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter trait.
        /// </summary>
        public static string HunterTrait {
            get {
                return ResourceManager.GetString("HunterTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from json file.
        /// </summary>
        public static string ImportFromJsonFile {
            get {
                return ResourceManager.GetString("ImportFromJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import UI configuration.
        /// </summary>
        public static string ImportUIConfig {
            get {
                return ResourceManager.GetString("ImportUIConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}{1}.
        /// </summary>
        public static string IndexFormat {
            get {
                return ResourceManager.GetString("IndexFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CutScene window.
        /// </summary>
        public static string IntercludeWindow {
            get {
                return ResourceManager.GetString("IntercludeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is game finished.
        /// </summary>
        public static string IsGameFinished {
            get {
                return ResourceManager.GetString("IsGameFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is visible.
        /// </summary>
        public static string IsVisible {
            get {
                return ResourceManager.GetString("IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        public static string ja_JP {
            get {
                return ResourceManager.GetString("ja_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is used for fast import. The example files are  neo-bpsys-wpf\Resources\队伍信息导入示例-xxx.json. Check the documentations for more details. .
        /// </summary>
        public static string JsonImportTip {
            get {
                return ResourceManager.GetString("JsonImportTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knockdowns.
        /// </summary>
        public static string Knockdowns {
            get {
                return ResourceManager.GetString("Knockdowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lakeside Village.
        /// </summary>
        public static string LakesideVillage {
            get {
                return ResourceManager.GetString("LakesideVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language setting.
        /// </summary>
        public static string LanguageSetting {
            get {
                return ResourceManager.GetString("LanguageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last step.
        /// </summary>
        public static string LastStep {
            get {
                return ResourceManager.GetString("LastStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leo&apos;s Memory.
        /// </summary>
        public static string LeosMemory {
            get {
                return ResourceManager.GetString("LeosMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen.
        /// </summary>
        public static string Listen {
            get {
                return ResourceManager.GetString("Listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by Zero_PLFJY.
        /// </summary>
        public static string MadeByZeroPLFJY {
            get {
                return ResourceManager.GetString("MadeByZeroPLFJY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map ban.
        /// </summary>
        public static string MapBan {
            get {
                return ResourceManager.GetString("MapBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map BP.
        /// </summary>
        public static string MapBP {
            get {
                return ResourceManager.GetString("MapBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map BP background.
        /// </summary>
        public static string MapBPBackground {
            get {
                return ResourceManager.GetString("MapBPBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map BP V2 background.
        /// </summary>
        public static string MapBPV2Background {
            get {
                return ResourceManager.GetString("MapBPV2Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapName.
        /// </summary>
        public static string MapName {
            get {
                return ResourceManager.GetString("MapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map name(Map BP).
        /// </summary>
        public static string MapNameInMapBP {
            get {
                return ResourceManager.GetString("MapNameInMapBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map name(Map BP V2).
        /// </summary>
        public static string MapNameInMapBPV2 {
            get {
                return ResourceManager.GetString("MapNameInMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map pick.
        /// </summary>
        public static string MapPick {
            get {
                return ResourceManager.GetString("MapPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match score.
        /// </summary>
        public static string MatchScore {
            get {
                return ResourceManager.GetString("MatchScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match scores.
        /// </summary>
        public static string MatchScores {
            get {
                return ResourceManager.GetString("MatchScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moonlit River Park.
        /// </summary>
        public static string MoonlitRiverPark {
            get {
                return ResourceManager.GetString("MoonlitRiverPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next step.
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Bans.
        /// </summary>
        public static string NoBans {
            get {
                return ResourceManager.GetString("NoBans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: All layout changes of score statistics will NOT be saved in BO3 mode.
        /// </summary>
        public static string NoteScoreStatisticsNotSaveInBO3Mode {
            get {
                return ResourceManager.GetString("NoteScoreStatisticsNotSaveInBO3Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official website.
        /// </summary>
        public static string OfficialWebsite {
            get {
                return ResourceManager.GetString("OfficialWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open all.
        /// </summary>
        public static string OpenAll {
            get {
                return ResourceManager.GetString("OpenAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the frontend config file directory.
        /// </summary>
        public static string OpenFrontendDirectory {
            get {
                return ResourceManager.GetString("OpenFrontendDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the game file output directory.
        /// </summary>
        public static string OpenGameFileDirectory {
            get {
                return ResourceManager.GetString("OpenGameFileDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log directory.
        /// </summary>
        public static string OpenLogDirectory {
            get {
                return ResourceManager.GetString("OpenLogDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open picking border | .
        /// </summary>
        public static string OpenPickingBorder {
            get {
                return ResourceManager.GetString("OpenPickingBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open source repositories used by our project: .
        /// </summary>
        public static string OpenSourceRepositoryUsed {
            get {
                return ResourceManager.GetString("OpenSourceRepositoryUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operate team: .
        /// </summary>
        public static string OperateTeam {
            get {
                return ResourceManager.GetString("OperateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallets destroyed.
        /// </summary>
        public static string PalletsDestroyed {
            get {
                return ResourceManager.GetString("PalletsDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet strikes.
        /// </summary>
        public static string PalletStrikes {
            get {
                return ResourceManager.GetString("PalletStrikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patroller.
        /// </summary>
        public static string Patroller {
            get {
                return ResourceManager.GetString("Patroller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peeper.
        /// </summary>
        public static string Peeper {
            get {
                return ResourceManager.GetString("Peeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick.
        /// </summary>
        public static string Pick {
            get {
                return ResourceManager.GetString("Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Character.
        /// </summary>
        public static string PickCharacter {
            get {
                return ResourceManager.GetString("PickCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick hunter.
        /// </summary>
        public static string PickHunter {
            get {
                return ResourceManager.GetString("PickHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking border color(MapBPV2).
        /// </summary>
        public static string PickingBorderColorOfMapBPV2 {
            get {
                return ResourceManager.GetString("PickingBorderColorOfMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking border image.
        /// </summary>
        public static string PickingBorderImage {
            get {
                return ResourceManager.GetString("PickingBorderImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking border image color(It will cover the color of picking border itself).
        /// </summary>
        public static string PickingBorderImageColor {
            get {
                return ResourceManager.GetString("PickingBorderImageColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking border(Map BP V2).
        /// </summary>
        public static string PickingBorderOfMapBPV2 {
            get {
                return ResourceManager.GetString("PickingBorderOfMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick survivor.
        /// </summary>
        public static string PickSurvivor {
            get {
                return ResourceManager.GetString("PickSurvivor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Pick&quot; word(Map BP).
        /// </summary>
        public static string PickWordInMapBP {
            get {
                return ResourceManager.GetString("PickWordInMapBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player ID.
        /// </summary>
        public static string PlayerID {
            get {
                return ResourceManager.GetString("PlayerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player name.
        /// </summary>
        public static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview: .
        /// </summary>
        public static string PreviewColon {
            get {
                return ResourceManager.GetString("PreviewColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project repository: .
        /// </summary>
        public static string ProjectRepository {
            get {
                return ResourceManager.GetString("ProjectRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick access.
        /// </summary>
        public static string QuickAccess {
            get {
                return ResourceManager.GetString("QuickAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining ciphers.
        /// </summary>
        public static string RemainingCiphers {
            get {
                return ResourceManager.GetString("RemainingCiphers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove photo.
        /// </summary>
        public static string RemovePhoto {
            get {
                return ResourceManager.GetString("RemovePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescues.
        /// </summary>
        public static string Rescues {
            get {
                return ResourceManager.GetString("Rescues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all personalization settings.
        /// </summary>
        public static string ResetAllPersonalizationSettings {
            get {
                return ResourceManager.GetString("ResetAllPersonalizationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all personalization settings of the window.
        /// </summary>
        public static string ResetAllPersonalizationSettingsOfTheWindow {
            get {
                return ResourceManager.GetString("ResetAllPersonalizationSettingsOfTheWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all scores.
        /// </summary>
        public static string ResetAllScores {
            get {
                return ResourceManager.GetString("ResetAllScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset BP overview layout.
        /// </summary>
        public static string ResetBPOverviewLayout {
            get {
                return ResourceManager.GetString("ResetBPOverviewLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset game scores.
        /// </summary>
        public static string ResetGameScores {
            get {
                return ResourceManager.GetString("ResetGameScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset hunter score layout in game.
        /// </summary>
        public static string ResetHunterScoreLayoutInGame {
            get {
                return ResourceManager.GetString("ResetHunterScoreLayoutInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset layout.
        /// </summary>
        public static string ResetLayout {
            get {
                return ResourceManager.GetString("ResetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset map BP.
        /// </summary>
        public static string ResetMapBP {
            get {
                return ResourceManager.GetString("ResetMapBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset map BP layout.
        /// </summary>
        public static string ResetMapBPLayout {
            get {
                return ResourceManager.GetString("ResetMapBPLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset map BP V2 layout.
        /// </summary>
        public static string ResetMapBPV2Layout {
            get {
                return ResourceManager.GetString("ResetMapBPV2Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset score statistics layout.
        /// </summary>
        public static string ResetScoreStatisticsLayout {
            get {
                return ResourceManager.GetString("ResetScoreStatisticsLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset survivor score layout in game.
        /// </summary>
        public static string ResetSurvivorScoreLayoutInGame {
            get {
                return ResourceManager.GetString("ResetSurvivorScoreLayoutInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacred Heart Hospital.
        /// </summary>
        public static string SacredHeartHospital {
            get {
                return ResourceManager.GetString("SacredHeartHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and apply.
        /// </summary>
        public static string SaveAndApply {
            get {
                return ResourceManager.GetString("SaveAndApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save game information.
        /// </summary>
        public static string SaveGameInformation {
            get {
                return ResourceManager.GetString("SaveGameInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score conponent.
        /// </summary>
        public static string ScoreComponent {
            get {
                return ResourceManager.GetString("ScoreComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Control.
        /// </summary>
        public static string ScoreControl {
            get {
                return ResourceManager.GetString("ScoreControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score in BP window and game.
        /// </summary>
        public static string ScoreInBPWindowAndGame {
            get {
                return ResourceManager.GetString("ScoreInBPWindowAndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}{2}{3}.
        /// </summary>
        public static string ScorePreview {
            get {
                return ResourceManager.GetString("ScorePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score settlement.
        /// </summary>
        public static string ScoreSettlement {
            get {
                return ResourceManager.GetString("ScoreSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores(Score Statistics).
        /// </summary>
        public static string ScoresInScoreStatistics {
            get {
                return ResourceManager.GetString("ScoresInScoreStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score statistics.
        /// </summary>
        public static string ScoreStatistics {
            get {
                return ResourceManager.GetString("ScoreStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score statistics(BO3 mode).
        /// </summary>
        public static string ScoreStatisticsBO3 {
            get {
                return ResourceManager.GetString("ScoreStatisticsBO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score statistics(BO5 mode).
        /// </summary>
        public static string ScoreStatisticsBO5 {
            get {
                return ResourceManager.GetString("ScoreStatisticsBO5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set photo.
        /// </summary>
        public static string SetPhoto {
            get {
                return ResourceManager.GetString("SetPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set team logo.
        /// </summary>
        public static string SetTeamLogo {
            get {
                return ResourceManager.GetString("SetTeamLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift distance of total score when switching between BO3 and BO5 mode.
        /// </summary>
        public static string ShiftDistanceOfTotalScoreWhenSwitchingBetweenBO3AndBO5Mode {
            get {
                return ResourceManager.GetString("ShiftDistanceOfTotalScoreWhenSwitchingBetweenBO3AndBO5Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show camp.
        /// </summary>
        public static string ShowCamp {
            get {
                return ResourceManager.GetString("ShowCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show picking border.
        /// </summary>
        public static string ShowPickingBorder {
            get {
                return ResourceManager.GetString("ShowPickingBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software updates.
        /// </summary>
        public static string SoftwareUpdates {
            get {
                return ResourceManager.GetString("SoftwareUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source of image resources: .
        /// </summary>
        public static string SourceOfImageResources {
            get {
                return ResourceManager.GetString("SourceOfImageResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor.
        /// </summary>
        public static string Sponsor {
            get {
                return ResourceManager.GetString("Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start game guidance.
        /// </summary>
        public static string StartGameGuidance {
            get {
                return ResourceManager.GetString("StartGameGuidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor.
        /// </summary>
        public static string Sur {
            get {
                return ResourceManager.GetString("Sur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor.
        /// </summary>
        public static string Survivor {
            get {
                return ResourceManager.GetString("Survivor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor data.
        /// </summary>
        public static string SurvivorData {
            get {
                return ResourceManager.GetString("SurvivorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor hits.
        /// </summary>
        public static string SurvivorHits {
            get {
                return ResourceManager.GetString("SurvivorHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor icon(Map BP V2).
        /// </summary>
        public static string SurvivorIconOfMapBPV2 {
            get {
                return ResourceManager.GetString("SurvivorIconOfMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor picking border 1st.
        /// </summary>
        public static string SurvivorPickingBorder1 {
            get {
                return ResourceManager.GetString("SurvivorPickingBorder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor picking border 1st &amp; 2nd.
        /// </summary>
        public static string SurvivorPickingBorder1and2 {
            get {
                return ResourceManager.GetString("SurvivorPickingBorder1and2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor picking border 2nd.
        /// </summary>
        public static string SurvivorPickingBorder2 {
            get {
                return ResourceManager.GetString("SurvivorPickingBorder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor picking border 3rd.
        /// </summary>
        public static string SurvivorPickingBorder3 {
            get {
                return ResourceManager.GetString("SurvivorPickingBorder3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor picking border 4th.
        /// </summary>
        public static string SurvivorPickingBorder4 {
            get {
                return ResourceManager.GetString("SurvivorPickingBorder4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor player.
        /// </summary>
        public static string SurvivorPlayer {
            get {
                return ResourceManager.GetString("SurvivorPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor player ID.
        /// </summary>
        public static string SurvivorPlayerID {
            get {
                return ResourceManager.GetString("SurvivorPlayerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor score in game.
        /// </summary>
        public static string SurvivorScoreInGame {
            get {
                return ResourceManager.GetString("SurvivorScoreInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor talent.
        /// </summary>
        public static string SurvivorTalent {
            get {
                return ResourceManager.GetString("SurvivorTalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap.
        /// </summary>
        public static string Swap {
            get {
                return ResourceManager.GetString("Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize to frontend.
        /// </summary>
        public static string SynchronizeToFrontend {
            get {
                return ResourceManager.GetString("SynchronizeToFrontend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talent &amp; Trait.
        /// </summary>
        public static string TalentAndTrait {
            get {
                return ResourceManager.GetString("TalentAndTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Information.
        /// </summary>
        public static string TeamInfo {
            get {
                return ResourceManager.GetString("TeamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name.
        /// </summary>
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name(BP Overview).
        /// </summary>
        public static string TeamNameInBPOverview {
            get {
                return ResourceManager.GetString("TeamNameInBPOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name(Map BP).
        /// </summary>
        public static string TeamNameInMapBP {
            get {
                return ResourceManager.GetString("TeamNameInMapBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name(Map BP V2).
        /// </summary>
        public static string TeamNameInMapBPV2 {
            get {
                return ResourceManager.GetString("TeamNameInMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name(Score Statistics).
        /// </summary>
        public static string TeamNameInScoreStatistics {
            get {
                return ResourceManager.GetString("TeamNameInScoreStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport.
        /// </summary>
        public static string Teleport {
            get {
                return ResourceManager.GetString("Teleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terror shocks.
        /// </summary>
        public static string TerrorShocks {
            get {
                return ResourceManager.GetString("TerrorShocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Red Church.
        /// </summary>
        public static string TheRedChurch {
            get {
                return ResourceManager.GetString("TheRedChurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Eliminate.
        /// </summary>
        public static string ThreeEliminate {
            get {
                return ResourceManager.GetString("ThreeEliminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Escape.
        /// </summary>
        public static string ThreeEscape {
            get {
                return ResourceManager.GetString("ThreeEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tie.
        /// </summary>
        public static string Tie {
            get {
                return ResourceManager.GetString("Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        public static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total game scores(Score Statistics).
        /// </summary>
        public static string TotalGameScoresInScoreStatistics {
            get {
                return ResourceManager.GetString("TotalGameScoresInScoreStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger GC collection manually.
        /// </summary>
        public static string TriggerGCCollectionManually {
            get {
                return ResourceManager.GetString("TriggerGCCollectionManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp.
        /// </summary>
        public static string Warp {
            get {
                return ResourceManager.GetString("Warp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string Widgets {
            get {
                return ResourceManager.GetString("Widgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        public static string zh_Hans {
            get {
                return ResourceManager.GetString("zh_Hans", resourceCulture);
            }
        }
    }
}
