//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neo_bpsys_wpf.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("neo_bpsys_wpf.Locales.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string _null {
            get {
                return ResourceManager.GetString("null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失常.
        /// </summary>
        public static string Abnormal {
            get {
                return ResourceManager.GetString("Abnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加选手.
        /// </summary>
        public static string AddPlayer {
            get {
                return ResourceManager.GetString("AddPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有前台窗口.
        /// </summary>
        public static string AllFrontendWindows {
            get {
                return ResourceManager.GetString("AllFrontendWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新一代的第五人格BP软件.
        /// </summary>
        public static string AModernIdentityVBPSoftware {
            get {
                return ResourceManager.GetString("AModernIdentityVBPSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否确认退出.
        /// </summary>
        public static string AreYouSureYouWantToExit {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 军工厂.
        /// </summary>
        public static string ArmsFactory {
            get {
                return ResourceManager.GetString("ArmsFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件作者：零风PLFJY | 作者QQ：3424127335 | 软件反馈群: 175741665.
        /// </summary>
        public static string AutherDetails {
            get {
                return ResourceManager.GetString("AutherDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客队.
        /// </summary>
        public static string AwayTeam {
            get {
                return ResourceManager.GetString("AwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客场小比分-1.
        /// </summary>
        public static string AwayTeamGameScoreMinus1 {
            get {
                return ResourceManager.GetString("AwayTeamGameScoreMinus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客场小比分+1.
        /// </summary>
        public static string AwayTeamGameScorePlus1 {
            get {
                return ResourceManager.GetString("AwayTeamGameScorePlus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客场队伍信息.
        /// </summary>
        public static string AwayTeamInformation {
            get {
                return ResourceManager.GetString("AwayTeamInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客场平-1.
        /// </summary>
        public static string AwayTeamTieMinus1 {
            get {
                return ResourceManager.GetString("AwayTeamTieMinus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客场平+1.
        /// </summary>
        public static string AwayTeamTiePlus1 {
            get {
                return ResourceManager.GetString("AwayTeamTiePlus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客场胜-1.
        /// </summary>
        public static string AwayTeamWinMinus1 {
            get {
                return ResourceManager.GetString("AwayTeamWinMinus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客场胜+1.
        /// </summary>
        public static string AwayTeamWinPlus1 {
            get {
                return ResourceManager.GetString("AwayTeamWinPlus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 后台管理.
        /// </summary>
        public static string Backend {
            get {
                return ResourceManager.GetString("Backend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用.
        /// </summary>
        public static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用监管者.
        /// </summary>
        public static string BanHunter {
            get {
                return ResourceManager.GetString("BanHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地图禁用.
        /// </summary>
        public static string BanMap {
            get {
                return ResourceManager.GetString("BanMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用数量控制.
        /// </summary>
        public static string BanNumberControl {
            get {
                return ResourceManager.GetString("BanNumberControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用求生者.
        /// </summary>
        public static string BanSurvivor {
            get {
                return ResourceManager.GetString("BanSurvivor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “禁用”文字（地图BP）.
        /// </summary>
        public static string BanWordInMapBP {
            get {
                return ResourceManager.GetString("BanWordInMapBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 黑色.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闪现.
        /// </summary>
        public static string Blink {
            get {
                return ResourceManager.GetString("Blink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP总览.
        /// </summary>
        public static string BPOverview {
            get {
                return ResourceManager.GetString("BPOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP窗口.
        /// </summary>
        public static string BPWindow {
            get {
                return ResourceManager.GetString("BPWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP背景.
        /// </summary>
        public static string BPWindowImages {
            get {
                return ResourceManager.GetString("BPWindowImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分数统计的阵营图标颜色.
        /// </summary>
        public static string CampIconColorInScoreStatistics {
            get {
                return ResourceManager.GetString("CampIconColorInScoreStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阵营图标颜色（地图BPV2）.
        /// </summary>
        public static string CampIconColorOfMapBPV2 {
            get {
                return ResourceManager.GetString("CampIconColorOfMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阵营名称（地图BP V2）.
        /// </summary>
        public static string CampNameInMapBPV2 {
            get {
                return ResourceManager.GetString("CampNameInMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客场队伍阵营.
        /// </summary>
        public static string CampOfAwayTeam {
            get {
                return ResourceManager.GetString("CampOfAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主场队伍阵营.
        /// </summary>
        public static string CampOfHomeTeam {
            get {
                return ResourceManager.GetString("CampOfHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色名称.
        /// </summary>
        public static string CharacterName {
            get {
                return ResourceManager.GetString("CharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查更新.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 唐人街.
        /// </summary>
        public static string ChinaTown {
            get {
                return ResourceManager.GetString("ChinaTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部关闭.
        /// </summary>
        public static string CloseAll {
            get {
                return ResourceManager.GetString("CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天赋与辅助特质图标颜色.
        /// </summary>
        public static string ColorOfTalentAndTraitIcon {
            get {
                return ResourceManager.GetString("ColorOfTalentAndTraitIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前面的区域以后再来探索吧~.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 牵制时长.
        /// </summary>
        public static string ContainmentTime {
            get {
                return ResourceManager.GetString("ContainmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 贡献者名单.
        /// </summary>
        public static string ContributorList {
            get {
                return ResourceManager.GetString("ContributorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分别控制前两个待选框.
        /// </summary>
        public static string ControlFirst2PickingBorderSeparately {
            get {
                return ResourceManager.GetString("ControlFirst2PickingBorderSeparately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手动控制.
        /// </summary>
        public static string ControlManually {
            get {
                return ResourceManager.GetString("ControlManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 倒计时.
        /// </summary>
        public static string CountDown {
            get {
                return ResourceManager.GetString("CountDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当局禁用.
        /// </summary>
        public static string CurrentBan {
            get {
                return ResourceManager.GetString("CurrentBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当局禁用锁.
        /// </summary>
        public static string CurrentBanLock {
            get {
                return ResourceManager.GetString("CurrentBanLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当局禁用锁（BP总览）.
        /// </summary>
        public static string CurrentBanLockOfBPOverview {
            get {
                return ResourceManager.GetString("CurrentBanLockOfBPOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前监管者队伍：.
        /// </summary>
        public static string CurrentHunterTeamColon {
            get {
                return ResourceManager.GetString("CurrentHunterTeamColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前上场选手.
        /// </summary>
        public static string CurrentPlayerOnStage {
            get {
                return ResourceManager.GetString("CurrentPlayerOnStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前状态：.
        /// </summary>
        public static string CurrentStatusColon {
            get {
                return ResourceManager.GetString("CurrentStatusColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前步骤：{0}.
        /// </summary>
        public static string CurrentStepFormat {
            get {
                return ResourceManager.GetString("CurrentStepFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前求生者队伍：.
        /// </summary>
        public static string CurrentSurvivorTeamColon {
            get {
                return ResourceManager.GetString("CurrentSurvivorTeamColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义BP窗口.
        /// </summary>
        public static string CustomizeBPWindow {
            get {
                return ResourceManager.GetString("CustomizeBPWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义前台UI.
        /// </summary>
        public static string CustomizeFrontendUI {
            get {
                return ResourceManager.GetString("CustomizeFrontendUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义赛后数据窗口.
        /// </summary>
        public static string CustomizeGameDataWindow {
            get {
                return ResourceManager.GetString("CustomizeGameDataWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义过场画面窗口.
        /// </summary>
        public static string CustomizeIntercludeWindow {
            get {
                return ResourceManager.GetString("CustomizeIntercludeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义比分窗口.
        /// </summary>
        public static string CustomizeScoreWindow {
            get {
                return ResourceManager.GetString("CustomizeScoreWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义小组件窗口.
        /// </summary>
        public static string CustomizeWidgetWindow {
            get {
                return ResourceManager.GetString("CustomizeWidgetWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不归林.
        /// </summary>
        public static string Darkwoods {
            get {
                return ResourceManager.GetString("Darkwoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调试选项.
        /// </summary>
        public static string DebugOptions {
            get {
                return ResourceManager.GetString("DebugOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 破译进度.
        /// </summary>
        public static string DecodingProgress {
            get {
                return ResourceManager.GetString("DecodingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设计模式.
        /// </summary>
        public static string DesignMode {
            get {
                return ResourceManager.GetString("DesignMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单位距离.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分配角色.
        /// </summary>
        public static string DistributeCharacters {
            get {
                return ResourceManager.GetString("DistributeCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看文档.
        /// </summary>
        public static string Documentations {
            get {
                return ResourceManager.GetString("Documentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载预览版？.
        /// </summary>
        public static string DownloadPreviewVersion {
            get {
                return ResourceManager.GetString("DownloadPreviewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载进度：.
        /// </summary>
        public static string DownloadProgress {
            get {
                return ResourceManager.GetString("DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载源：.
        /// </summary>
        public static string DownloadSource {
            get {
                return ResourceManager.GetString("DownloadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改赛后数据背景图片.
        /// </summary>
        public static string EditGameDataBackgroundImage {
            get {
                return ResourceManager.GetString("EditGameDataBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改图片.
        /// </summary>
        public static string EditImage {
            get {
                return ResourceManager.GetString("EditImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改过场画面背景图片.
        /// </summary>
        public static string EditIntercludeBackgroundImage {
            get {
                return ResourceManager.GetString("EditIntercludeBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑文字属性.
        /// </summary>
        public static string EditTextProperty {
            get {
                return ResourceManager.GetString("EditTextProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (United States).
        /// </summary>
        public static string en_US {
            get {
                return ResourceManager.GetString("en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束对局引导.
        /// </summary>
        public static string EndGameGuidance {
            get {
                return ResourceManager.GetString("EndGameGuidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上场.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 永眠镇.
        /// </summary>
        public static string EversleepingTown {
            get {
                return ResourceManager.GetString("EversleepingTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 兴奋.
        /// </summary>
        public static string Excitement {
            get {
                return ResourceManager.GetString("Excitement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下场.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出UI配置.
        /// </summary>
        public static string ExportUIConfig {
            get {
                return ResourceManager.GetString("ExportUIConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扩展功能.
        /// </summary>
        public static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随系统.
        /// </summary>
        public static string FollowSystem {
            get {
                return ResourceManager.GetString("FollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赛制：.
        /// </summary>
        public static string FormatColon {
            get {
                return ResourceManager.GetString("FormatColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4抓.
        /// </summary>
        public static string FourEliminate {
            get {
                return ResourceManager.GetString("FourEliminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4跑.
        /// </summary>
        public static string FourEscape {
            get {
                return ResourceManager.GetString("FourEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自由对局.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前台-BP.
        /// </summary>
        public static string FrontendBP {
            get {
                return ResourceManager.GetString("FrontendBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前台-过场画面.
        /// </summary>
        public static string FrontendCutScene {
            get {
                return ResourceManager.GetString("FrontendCutScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前台管理.
        /// </summary>
        public static string FrontendManagement {
            get {
                return ResourceManager.GetString("FrontendManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前台-小组件.
        /// </summary>
        public static string FrontendWidgets {
            get {
                return ResourceManager.GetString("FrontendWidgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第1局上半.
        /// </summary>
        public static string Game1FirstHalf {
            get {
                return ResourceManager.GetString("Game1FirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第1局下半.
        /// </summary>
        public static string Game1SecondHalf {
            get {
                return ResourceManager.GetString("Game1SecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第2局上半.
        /// </summary>
        public static string Game2FirstHalf {
            get {
                return ResourceManager.GetString("Game2FirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第2局下半.
        /// </summary>
        public static string Game2SecondHalf {
            get {
                return ResourceManager.GetString("Game2SecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第3局加赛上半.
        /// </summary>
        public static string Game3ExtraFirstHalf {
            get {
                return ResourceManager.GetString("Game3ExtraFirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第3局加赛下半.
        /// </summary>
        public static string Game3ExtraSecondHalf {
            get {
                return ResourceManager.GetString("Game3ExtraSecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第3局上半.
        /// </summary>
        public static string Game3FirstHalf {
            get {
                return ResourceManager.GetString("Game3FirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第3局下半.
        /// </summary>
        public static string Game3SecondHalf {
            get {
                return ResourceManager.GetString("Game3SecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第4局上半.
        /// </summary>
        public static string Game4FirstHalf {
            get {
                return ResourceManager.GetString("Game4FirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第4局下半.
        /// </summary>
        public static string Game4SecondHalf {
            get {
                return ResourceManager.GetString("Game4SecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第5局加赛上半.
        /// </summary>
        public static string Game5ExtraFirstHalf {
            get {
                return ResourceManager.GetString("Game5ExtraFirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第5局加赛下半.
        /// </summary>
        public static string Game5ExtraSecondHalf {
            get {
                return ResourceManager.GetString("Game5ExtraSecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第5局上半.
        /// </summary>
        public static string Game5FirstHalf {
            get {
                return ResourceManager.GetString("Game5FirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第5局下半.
        /// </summary>
        public static string Game5SecondHalf {
            get {
                return ResourceManager.GetString("Game5SecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赛后数据.
        /// </summary>
        public static string GameData {
            get {
                return ResourceManager.GetString("GameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对局进度.
        /// </summary>
        public static string GameProgress {
            get {
                return ResourceManager.GetString("GameProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对局进度：.
        /// </summary>
        public static string GameProgressColon {
            get {
                return ResourceManager.GetString("GameProgressColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对局进度（BP总览）.
        /// </summary>
        public static string GameProgressInBPOverview {
            get {
                return ResourceManager.GetString("GameProgressInBPOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对局结果.
        /// </summary>
        public static string GameResult {
            get {
                return ResourceManager.GetString("GameResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小比分.
        /// </summary>
        public static string GameScores {
            get {
                return ResourceManager.GetString("GameScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小比分（BP总览）.
        /// </summary>
        public static string GameScoresInBPOverview {
            get {
                return ResourceManager.GetString("GameScoresInBPOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小比分（分数统计）.
        /// </summary>
        public static string GameScoresInScoreStatistics {
            get {
                return ResourceManager.GetString("GameScoresInScoreStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 场次选择.
        /// </summary>
        public static string GameSelection {
            get {
                return ResourceManager.GetString("GameSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赛后数据窗口.
        /// </summary>
        public static string GameStatisticsWindow {
            get {
                return ResourceManager.GetString("GameStatisticsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全局禁用.
        /// </summary>
        public static string GlobalBan {
            get {
                return ResourceManager.GetString("GlobalBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全局禁用监管者.
        /// </summary>
        public static string GlobalBanHunter {
            get {
                return ResourceManager.GetString("GlobalBanHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全局禁用锁.
        /// </summary>
        public static string GlobalBanLock {
            get {
                return ResourceManager.GetString("GlobalBanLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全局禁用锁（BP总览）.
        /// </summary>
        public static string GlobalBanLockOfBPOverview {
            get {
                return ResourceManager.GetString("GlobalBanLockOfBPOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全局禁选记录.
        /// </summary>
        public static string GlobalBanRecord {
            get {
                return ResourceManager.GetString("GlobalBanRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全局禁用求生者.
        /// </summary>
        public static string GlobalBanSurvivor {
            get {
                return ResourceManager.GetString("GlobalBanSurvivor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 治疗次数.
        /// </summary>
        public static string Heals {
            get {
                return ResourceManager.GetString("Heals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动页.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主队.
        /// </summary>
        public static string HomeTeam {
            get {
                return ResourceManager.GetString("HomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主场小比分-1.
        /// </summary>
        public static string HomeTeamGameScoreMinus1 {
            get {
                return ResourceManager.GetString("HomeTeamGameScoreMinus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主场小比分+1.
        /// </summary>
        public static string HomeTeamGameScorePlus1 {
            get {
                return ResourceManager.GetString("HomeTeamGameScorePlus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主场队伍信息.
        /// </summary>
        public static string HomeTeamInformation {
            get {
                return ResourceManager.GetString("HomeTeamInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主队名称.
        /// </summary>
        public static string HomeTeamName {
            get {
                return ResourceManager.GetString("HomeTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主场平-1.
        /// </summary>
        public static string HomeTeamTieMinus1 {
            get {
                return ResourceManager.GetString("HomeTeamTieMinus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主场平+1.
        /// </summary>
        public static string HomeTeamTiePlus1 {
            get {
                return ResourceManager.GetString("HomeTeamTiePlus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主场胜-1.
        /// </summary>
        public static string HomeTeamWinMinus1 {
            get {
                return ResourceManager.GetString("HomeTeamWinMinus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主场胜+1.
        /// </summary>
        public static string HomeTeamWinPlus1 {
            get {
                return ResourceManager.GetString("HomeTeamWinPlus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监管者.
        /// </summary>
        public static string Hun {
            get {
                return ResourceManager.GetString("Hun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监管者.
        /// </summary>
        public static string Hunter {
            get {
                return ResourceManager.GetString("Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监管者数据.
        /// </summary>
        public static string HunterData {
            get {
                return ResourceManager.GetString("HunterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监管者图标（地图BP V2）.
        /// </summary>
        public static string HunterIconOfMapBPV2 {
            get {
                return ResourceManager.GetString("HunterIconOfMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监管者待选框.
        /// </summary>
        public static string HunterPickingBorder {
            get {
                return ResourceManager.GetString("HunterPickingBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监管者选手.
        /// </summary>
        public static string HunterPlayer {
            get {
                return ResourceManager.GetString("HunterPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监管者选手ID.
        /// </summary>
        public static string HunterPlayerID {
            get {
                return ResourceManager.GetString("HunterPlayerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏内监管者比分.
        /// </summary>
        public static string HunterScoreInGame {
            get {
                return ResourceManager.GetString("HunterScoreInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监管者天赋.
        /// </summary>
        public static string HunterTalent {
            get {
                return ResourceManager.GetString("HunterTalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监管者辅助特质.
        /// </summary>
        public static string HunterTrait {
            get {
                return ResourceManager.GetString("HunterTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从json文件导入.
        /// </summary>
        public static string ImportFromJsonFile {
            get {
                return ResourceManager.GetString("ImportFromJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入UI配置.
        /// </summary>
        public static string ImportUIConfig {
            get {
                return ResourceManager.GetString("ImportUIConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} 号位.
        /// </summary>
        public static string IndexFormat {
            get {
                return ResourceManager.GetString("IndexFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过场画面.
        /// </summary>
        public static string IntercludeWindow {
            get {
                return ResourceManager.GetString("IntercludeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对局已完成.
        /// </summary>
        public static string IsGameFinished {
            get {
                return ResourceManager.GetString("IsGameFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否显示.
        /// </summary>
        public static string IsVisible {
            get {
                return ResourceManager.GetString("IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        public static string ja_JP {
            get {
                return ResourceManager.GetString("ja_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这是用于快速导入队伍信息使用的，示例文件是软件目录下的neo-bpsys-wpf\Resources\队伍信息导入示例-xxx.json，有其它问题请查阅文档.
        /// </summary>
        public static string JsonImportTip {
            get {
                return ResourceManager.GetString("JsonImportTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 击倒次数.
        /// </summary>
        public static string Knockdowns {
            get {
                return ResourceManager.GetString("Knockdowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 湖景村.
        /// </summary>
        public static string LakesideVillage {
            get {
                return ResourceManager.GetString("LakesideVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言设置.
        /// </summary>
        public static string LanguageSetting {
            get {
                return ResourceManager.GetString("LanguageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一步.
        /// </summary>
        public static string LastStep {
            get {
                return ResourceManager.GetString("LastStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 里奥的回忆.
        /// </summary>
        public static string LeosMemory {
            get {
                return ResourceManager.GetString("LeosMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聆听.
        /// </summary>
        public static string Listen {
            get {
                return ResourceManager.GetString("Listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by 零风PLFJY.
        /// </summary>
        public static string MadeByZeroPLFJY {
            get {
                return ResourceManager.GetString("MadeByZeroPLFJY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地图禁选.
        /// </summary>
        public static string MapBP {
            get {
                return ResourceManager.GetString("MapBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地图BP背景.
        /// </summary>
        public static string MapBPBackground {
            get {
                return ResourceManager.GetString("MapBPBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地图BPV2背景.
        /// </summary>
        public static string MapBPV2Background {
            get {
                return ResourceManager.GetString("MapBPV2Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地图名称.
        /// </summary>
        public static string MapName {
            get {
                return ResourceManager.GetString("MapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地图名称（地图BP）.
        /// </summary>
        public static string MapNameInMapBP {
            get {
                return ResourceManager.GetString("MapNameInMapBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地图名称（地图BP V2）.
        /// </summary>
        public static string MapNameInMapBPV2 {
            get {
                return ResourceManager.GetString("MapNameInMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大比分.
        /// </summary>
        public static string MatchScore {
            get {
                return ResourceManager.GetString("MatchScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大比分.
        /// </summary>
        public static string MatchScores {
            get {
                return ResourceManager.GetString("MatchScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月亮河公园.
        /// </summary>
        public static string MoonlitRiverPark {
            get {
                return ResourceManager.GetString("MoonlitRiverPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新对局.
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一局.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一步.
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无禁用.
        /// </summary>
        public static string NoBans {
            get {
                return ResourceManager.GetString("NoBans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注：在 BO3 模式下，所有分数统计的布局修改将【不会】被保存.
        /// </summary>
        public static string NoteScoreStatisticsNotSaveInBO3Mode {
            get {
                return ResourceManager.GetString("NoteScoreStatisticsNotSaveInBO3Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前往官网.
        /// </summary>
        public static string OfficialWebsite {
            get {
                return ResourceManager.GetString("OfficialWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部启动.
        /// </summary>
        public static string OpenAll {
            get {
                return ResourceManager.GetString("OpenAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开前台配置文件目录.
        /// </summary>
        public static string OpenFrontendDirectory {
            get {
                return ResourceManager.GetString("OpenFrontendDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开对局文件输出目录.
        /// </summary>
        public static string OpenGameFileDirectory {
            get {
                return ResourceManager.GetString("OpenGameFileDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开日志目录.
        /// </summary>
        public static string OpenLogDirectory {
            get {
                return ResourceManager.GetString("OpenLogDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用待选框 | .
        /// </summary>
        public static string OpenPickingBorder {
            get {
                return ResourceManager.GetString("OpenPickingBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以下是本软件使用的开源代码库：.
        /// </summary>
        public static string OpenSourceRepositoryUsed {
            get {
                return ResourceManager.GetString("OpenSourceRepositoryUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作队伍：.
        /// </summary>
        public static string OperateTeam {
            get {
                return ResourceManager.GetString("OperateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 破坏板子数.
        /// </summary>
        public static string PalletsDestroyed {
            get {
                return ResourceManager.GetString("PalletsDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 砸板命中次数.
        /// </summary>
        public static string PalletStrikes {
            get {
                return ResourceManager.GetString("PalletStrikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 巡视者.
        /// </summary>
        public static string Patroller {
            get {
                return ResourceManager.GetString("Patroller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窥视者.
        /// </summary>
        public static string Peeper {
            get {
                return ResourceManager.GetString("Peeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择.
        /// </summary>
        public static string Pick {
            get {
                return ResourceManager.GetString("Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择阵营.
        /// </summary>
        public static string PickCamp {
            get {
                return ResourceManager.GetString("PickCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择角色.
        /// </summary>
        public static string PickCharacter {
            get {
                return ResourceManager.GetString("PickCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择监管者天赋.
        /// </summary>
        public static string PickHunTalent {
            get {
                return ResourceManager.GetString("PickHunTalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择监管者.
        /// </summary>
        public static string PickHunter {
            get {
                return ResourceManager.GetString("PickHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 待选框颜色（地图BP V2）.
        /// </summary>
        public static string PickingBorderColorOfMapBPV2 {
            get {
                return ResourceManager.GetString("PickingBorderColorOfMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 待选框.
        /// </summary>
        public static string PickingBorderImage {
            get {
                return ResourceManager.GetString("PickingBorderImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 待选框边缘颜色（覆盖贴图颜色）.
        /// </summary>
        public static string PickingBorderImageColor {
            get {
                return ResourceManager.GetString("PickingBorderImageColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 待选框（地图BP V2）.
        /// </summary>
        public static string PickingBorderOfMapBPV2 {
            get {
                return ResourceManager.GetString("PickingBorderOfMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地图选择.
        /// </summary>
        public static string PickMap {
            get {
                return ResourceManager.GetString("PickMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择求生者天赋.
        /// </summary>
        public static string PickSurTalent {
            get {
                return ResourceManager.GetString("PickSurTalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择求生者.
        /// </summary>
        public static string PickSurvivor {
            get {
                return ResourceManager.GetString("PickSurvivor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “选用”文字（地图BP）.
        /// </summary>
        public static string PickWordInMapBP {
            get {
                return ResourceManager.GetString("PickWordInMapBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选手ID.
        /// </summary>
        public static string PlayerID {
            get {
                return ResourceManager.GetString("PlayerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选手名称.
        /// </summary>
        public static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览：.
        /// </summary>
        public static string PreviewColon {
            get {
                return ResourceManager.GetString("PreviewColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目仓库：.
        /// </summary>
        public static string ProjectRepository {
            get {
                return ResourceManager.GetString("ProjectRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快捷入口.
        /// </summary>
        public static string QuickAccess {
            get {
                return ResourceManager.GetString("QuickAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剩余密码机数量.
        /// </summary>
        public static string RemainingCiphers {
            get {
                return ResourceManager.GetString("RemainingCiphers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除定妆照.
        /// </summary>
        public static string RemovePhoto {
            get {
                return ResourceManager.GetString("RemovePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 救人次数.
        /// </summary>
        public static string Rescues {
            get {
                return ResourceManager.GetString("Rescues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置全部个性化设置.
        /// </summary>
        public static string ResetAllPersonalizationSettings {
            get {
                return ResourceManager.GetString("ResetAllPersonalizationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置该窗口全部个性化设置.
        /// </summary>
        public static string ResetAllPersonalizationSettingsOfTheWindow {
            get {
                return ResourceManager.GetString("ResetAllPersonalizationSettingsOfTheWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总清零.
        /// </summary>
        public static string ResetAllScores {
            get {
                return ResourceManager.GetString("ResetAllScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置BP总览布局.
        /// </summary>
        public static string ResetBPOverviewLayout {
            get {
                return ResourceManager.GetString("ResetBPOverviewLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小比分清零.
        /// </summary>
        public static string ResetGameScores {
            get {
                return ResourceManager.GetString("ResetGameScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置游戏内监管者比分布局.
        /// </summary>
        public static string ResetHunterScoreLayoutInGame {
            get {
                return ResourceManager.GetString("ResetHunterScoreLayoutInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置布局.
        /// </summary>
        public static string ResetLayout {
            get {
                return ResourceManager.GetString("ResetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置地图BP.
        /// </summary>
        public static string ResetMapBP {
            get {
                return ResourceManager.GetString("ResetMapBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置地图BP布局.
        /// </summary>
        public static string ResetMapBPLayout {
            get {
                return ResourceManager.GetString("ResetMapBPLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置地图BP V2布局.
        /// </summary>
        public static string ResetMapBPV2Layout {
            get {
                return ResourceManager.GetString("ResetMapBPV2Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置分数统计布局.
        /// </summary>
        public static string ResetScoreStatisticsLayout {
            get {
                return ResourceManager.GetString("ResetScoreStatisticsLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置游戏内求生者比分布局.
        /// </summary>
        public static string ResetSurvivorScoreLayoutInGame {
            get {
                return ResourceManager.GetString("ResetSurvivorScoreLayoutInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圣心医院.
        /// </summary>
        public static string SacredHeartHospital {
            get {
                return ResourceManager.GetString("SacredHeartHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存并应用.
        /// </summary>
        public static string SaveAndApply {
            get {
                return ResourceManager.GetString("SaveAndApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存当前对局进度.
        /// </summary>
        public static string SaveGameInformation {
            get {
                return ResourceManager.GetString("SaveGameInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 比分组件.
        /// </summary>
        public static string ScoreComponent {
            get {
                return ResourceManager.GetString("ScoreComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 比分控制.
        /// </summary>
        public static string ScoreControl {
            get {
                return ResourceManager.GetString("ScoreControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP界面及游戏内比分.
        /// </summary>
        public static string ScoreInBPWindowAndGame {
            get {
                return ResourceManager.GetString("ScoreInBPWindowAndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  W:{1} D:{2}  小比分: {3}.
        /// </summary>
        public static string ScorePreview {
            get {
                return ResourceManager.GetString("ScorePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大比分结算.
        /// </summary>
        public static string ScoreSettlement {
            get {
                return ResourceManager.GetString("ScoreSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分数（分数统计）.
        /// </summary>
        public static string ScoresInScoreStatistics {
            get {
                return ResourceManager.GetString("ScoresInScoreStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分数统计.
        /// </summary>
        public static string ScoreStatistics {
            get {
                return ResourceManager.GetString("ScoreStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分数统计（BO3）.
        /// </summary>
        public static string ScoreStatisticsBO3 {
            get {
                return ResourceManager.GetString("ScoreStatisticsBO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分数统计（BO5）.
        /// </summary>
        public static string ScoreStatisticsBO5 {
            get {
                return ResourceManager.GetString("ScoreStatisticsBO5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置定妆照.
        /// </summary>
        public static string SetPhoto {
            get {
                return ResourceManager.GetString("SetPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置队伍logo.
        /// </summary>
        public static string SetTeamLogo {
            get {
                return ResourceManager.GetString("SetTeamLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BO3 和 BO5 模式切换时总分组件平移距离.
        /// </summary>
        public static string ShiftDistanceOfTotalScoreWhenSwitchingBetweenBO3AndBO5Mode {
            get {
                return ResourceManager.GetString("ShiftDistanceOfTotalScoreWhenSwitchingBetweenBO3AndBO5Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示阵营.
        /// </summary>
        public static string ShowCamp {
            get {
                return ResourceManager.GetString("ShowCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 待选框开关.
        /// </summary>
        public static string ShowPickingBorder {
            get {
                return ResourceManager.GetString("ShowPickingBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用更新.
        /// </summary>
        public static string SoftwareUpdates {
            get {
                return ResourceManager.GetString("SoftwareUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 贴图素材来自：.
        /// </summary>
        public static string SourceOfImageResources {
            get {
                return ResourceManager.GetString("SourceOfImageResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赞助渠道.
        /// </summary>
        public static string Sponsor {
            get {
                return ResourceManager.GetString("Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始对局引导.
        /// </summary>
        public static string StartGameGuidance {
            get {
                return ResourceManager.GetString("StartGameGuidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 求生者.
        /// </summary>
        public static string Sur {
            get {
                return ResourceManager.GetString("Sur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 求生者.
        /// </summary>
        public static string Survivor {
            get {
                return ResourceManager.GetString("Survivor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 求生者数据.
        /// </summary>
        public static string SurvivorData {
            get {
                return ResourceManager.GetString("SurvivorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命中求生者次数.
        /// </summary>
        public static string SurvivorHits {
            get {
                return ResourceManager.GetString("SurvivorHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 求生者图标（地图BP V2）.
        /// </summary>
        public static string SurvivorIconOfMapBPV2 {
            get {
                return ResourceManager.GetString("SurvivorIconOfMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 求生者待选框1.
        /// </summary>
        public static string SurvivorPickingBorder1 {
            get {
                return ResourceManager.GetString("SurvivorPickingBorder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 求生者待选框1 &amp; 2.
        /// </summary>
        public static string SurvivorPickingBorder1and2 {
            get {
                return ResourceManager.GetString("SurvivorPickingBorder1and2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 求生者待选框2.
        /// </summary>
        public static string SurvivorPickingBorder2 {
            get {
                return ResourceManager.GetString("SurvivorPickingBorder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 求生者待选框3.
        /// </summary>
        public static string SurvivorPickingBorder3 {
            get {
                return ResourceManager.GetString("SurvivorPickingBorder3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 求生者待选框4.
        /// </summary>
        public static string SurvivorPickingBorder4 {
            get {
                return ResourceManager.GetString("SurvivorPickingBorder4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 求生者选手.
        /// </summary>
        public static string SurvivorPlayer {
            get {
                return ResourceManager.GetString("SurvivorPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 求生者选手ID.
        /// </summary>
        public static string SurvivorPlayerID {
            get {
                return ResourceManager.GetString("SurvivorPlayerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏内求生者比分.
        /// </summary>
        public static string SurvivorScoreInGame {
            get {
                return ResourceManager.GetString("SurvivorScoreInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 求生者天赋.
        /// </summary>
        public static string SurvivorTalent {
            get {
                return ResourceManager.GetString("SurvivorTalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交换阵营.
        /// </summary>
        public static string Swap {
            get {
                return ResourceManager.GetString("Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步至前台.
        /// </summary>
        public static string SynchronizeToFrontend {
            get {
                return ResourceManager.GetString("SynchronizeToFrontend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天赋特质.
        /// </summary>
        public static string TalentAndTrait {
            get {
                return ResourceManager.GetString("TalentAndTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 队伍信息.
        /// </summary>
        public static string TeamInfo {
            get {
                return ResourceManager.GetString("TeamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 队伍名称.
        /// </summary>
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 队伍名称（BP概览）.
        /// </summary>
        public static string TeamNameInBPOverview {
            get {
                return ResourceManager.GetString("TeamNameInBPOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 队伍名称（地图BP）.
        /// </summary>
        public static string TeamNameInMapBP {
            get {
                return ResourceManager.GetString("TeamNameInMapBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 队伍名称（地图BP V2）.
        /// </summary>
        public static string TeamNameInMapBPV2 {
            get {
                return ResourceManager.GetString("TeamNameInMapBPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 队伍名称（分数统计）.
        /// </summary>
        public static string TeamNameInScoreStatistics {
            get {
                return ResourceManager.GetString("TeamNameInScoreStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 传送.
        /// </summary>
        public static string Teleport {
            get {
                return ResourceManager.GetString("Teleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 恐惧震慑次数.
        /// </summary>
        public static string TerrorShocks {
            get {
                return ResourceManager.GetString("TerrorShocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 红教堂.
        /// </summary>
        public static string TheRedChurch {
            get {
                return ResourceManager.GetString("TheRedChurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3抓.
        /// </summary>
        public static string ThreeEliminate {
            get {
                return ResourceManager.GetString("ThreeEliminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3跑.
        /// </summary>
        public static string ThreeEscape {
            get {
                return ResourceManager.GetString("ThreeEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平局.
        /// </summary>
        public static string Tie {
            get {
                return ResourceManager.GetString("Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计时器.
        /// </summary>
        public static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总小比分（分数统计）.
        /// </summary>
        public static string TotalGameScoresInScoreStatistics {
            get {
                return ResourceManager.GetString("TotalGameScoresInScoreStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手动触发GC回收.
        /// </summary>
        public static string TriggerGCCollectionManually {
            get {
                return ResourceManager.GetString("TriggerGCCollectionManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移形.
        /// </summary>
        public static string Warp {
            get {
                return ResourceManager.GetString("Warp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 白色.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小组件（地图BP等）.
        /// </summary>
        public static string Widgets {
            get {
                return ResourceManager.GetString("Widgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        public static string zh_Hans {
            get {
                return ResourceManager.GetString("zh_Hans", resourceCulture);
            }
        }
    }
}
